/*
 * DebateRecordDate.java
 *
 * Created on August 11, 2008, 10:06 PM
 */

package org.bungeni.editor.selectors.debaterecord.masthead;

import java.awt.Component;
import org.bungeni.editor.selectors.BaseMetadataPanel;

/**
 *
 * @author  undesa
 */
public class DebateRecordDate extends BaseMetadataPanel {

      private static org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger(DebateRecordDate.class.getName());

    /** Creates new form DebateRecordDate */
    public DebateRecordDate() {
        super();
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_initdebate_hansard = new javax.swing.JLabel();
        dt_initdebate_hansard = new org.jdesktop.swingx.JXDatePicker();

        lbl_initdebate_hansard.setText("DebateRecord Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dt_initdebate_hansard, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(lbl_initdebate_hansard, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lbl_initdebate_hansard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(dt_initdebate_hansard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getAccessibleContext().setAccessibleName("DebateRecord Date");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker dt_initdebate_hansard;
    private javax.swing.JLabel lbl_initdebate_hansard;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getPanelName() {
        return this.getAccessibleContext().getAccessibleName();
    }

    @Override
    public Component getPanelComponent() {
       return this;
    }

    @Override
    public boolean preFullEdit() {
       return true;
    }

    @Override
    public boolean processFullEdit() {
       return true;    }

    @Override
    public boolean postFullEdit() {
       return true;    }

    @Override
    public boolean preFullInsert() {
       return true;    }

    @Override
    public boolean processFullInsert() {
       return true;
    }

    @Override
    public boolean postFullInsert() {
       return true;
    }

    @Override
    public boolean preSelectEdit() {
       return true;
    }

    @Override
    public boolean processSelectEdit() {
       return true;
    }

    @Override
    public boolean postSelectEdit() {
       return true;
    }

    @Override
    public boolean preSelectInsert() {
       return true;
    }

    @Override
    public boolean processSelectInsert() {
       return true;
    }

    @Override
    public boolean postSelectInsert() {
       return true;
    }

    @Override
    public boolean validateSelectedEdit() {
       return true;
    }

    @Override
    public boolean validateSelectedInsert() {
       return true;
    }

    @Override
    public boolean validateFullInsert() {
       return true;
    }

    @Override
    public boolean validateFullEdit() {
       return true;
    }

    @Override
    public boolean doCancel() {
       return true;
    }

    @Override
    public boolean doReset() {
       return true;
    }

    @Override
    protected void initFieldsSelectedEdit() {
        return;
    }

    @Override
    protected void initFieldsSelectedInsert() {
        return;
    }

    @Override
    protected void initFieldsInsert() {
        return;
    }

    @Override
    protected void initFieldsEdit() {
        return;
    }

}
