/*
 * BungeniRuleElement.idl
 *
 * Created on 17.01.2007 - 22:51:56
 *
 */

#ifndef __org_openoffice_bungenivalidator_BungeniRuleElement__
#define __org_openoffice_bungenivalidator_BungeniRuleElement__


/*
This struct defines the property returned to StarBasic

the Rule Element property is marshalled with the StarBasic interpreter using this property
this struct can be logically mapped to the RuleXMLElement class
*/



module org { module openoffice { module bungenivalidator {
    struct BungeniRuleElement {
         string ElementName; //name of element 
         string RuleElementType; //block or tag
         string ElementType; //repeat or none
         string MaxOccurs;
         string ParentElement; //parent element of current element
         string NextElement; //hash index to next element
         string PreviousElement; //hash index to previous element

    };
}; }; };

#endif
