/*
 * BungeniRuleElement.idl
 *
 * Created on 17.01.2007 - 22:51:56
 *
 */

#ifndef __org_openoffice_rssreader_BungeniRssHeader__
#define __org_openoffice_rssreader_BungeniRssHeader__


/*
This struct defines the property returned to StarBasic

the Rule Element property is marshalled with the StarBasic interpreter using this property
this struct can be logically mapped to the RuleXMLElement class
*/



module org { module openoffice { module rssreader {
    struct BungeniRssHeader {
         string channelTitle; //name of element 
         string channelURL; //block or tag
         string channelDescription; //repeat or none
         string channelLanguage;
         string channelGenerator; //parent element of current element
 
    };
}; }; };

#endif

