/*
 * ooProxyPanel.java
 *
 * Created on September 20, 2007, 12:14 PM
 */

package org.bungeni.ooo.proxy;

import com.sun.star.lang.XComponent;
import com.sun.star.uno.XComponentContext;
import java.util.ArrayList;
import org.bungeni.ooo.OOComponentHelper;

/**
 *
 * @author  Administrator
 */
public class ooProxyPanel extends javax.swing.JPanel {
    XComponentContext componentContext = null;
    ArrayList<OOComponentHelper> instances = new ArrayList<OOComponentHelper>();
    org.bungeni.ooo.BungenioOoHelper openofficeObject = null;
 
    /** Creates new form ooProxyPanel */
    public ooProxyPanel() {
        initComponents();
    }
    
    public ooProxyPanel(XComponentContext xContext, String URL) {
        componentContext = xContext;
        openofficeObject = new org.bungeni.ooo.BungenioOoHelper(componentContext);
        openofficeObject.initoOo();
        addComponent(URL);
    }
    
    public void addComponent(String URL){
        XComponent xComponent;
        xComponent = openofficeObject.openDocument(URL);
        OOComponentHelper ooDocument = new OOComponentHelper(xComponent, componentContext);
        instances.add(ooDocument);
        jTextArea1.append("launching: "+ URL);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jLabel1.setText("openoffice - zopeedit - proxy application");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 234, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(25, 25, 25)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    
}
