/*
 * numberSchemePanel.java
 *
 * Created on March 26, 2008, 3:46 PM
 */

package org.numbering.dialogs;

/**
 *
 * @author  undesa
 */
public class numberSchemePanel extends javax.swing.JPanel {
    
    /** Creates new form numberSchemePanel */
    public numberSchemePanel() {
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        comboNumberingSchemes = new javax.swing.JComboBox();
        labelNumberingScheme = new javax.swing.JLabel();
        buttonApplyNumberingScheme = new javax.swing.JButton();
        txtSectionType = new javax.swing.JTextField();

        comboNumberingSchemes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Base Numbering", "Decimal Numbering", "Alphabet" }));

        labelNumberingScheme.setText("Please select a numbering scheme and click apply");

        buttonApplyNumberingScheme.setText("Apply Numbering Scheme");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(48, 48, 48)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(labelNumberingScheme)
                    .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, txtSectionType)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, comboNumberingSchemes, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, buttonApplyNumberingScheme, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(labelNumberingScheme)
                .add(14, 14, 14)
                .add(comboNumberingSchemes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(24, 24, 24)
                .add(buttonApplyNumberingScheme)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 18, Short.MAX_VALUE)
                .add(txtSectionType, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonApplyNumberingScheme;
    private javax.swing.JComboBox comboNumberingSchemes;
    private javax.swing.JLabel labelNumberingScheme;
    private javax.swing.JTextField txtSectionType;
    // End of variables declaration//GEN-END:variables
    
}
