#!/bin/sh
#===============================================================================
#
#          FILE:  postrm
#
#   DESCRIPTION:  Update post remove script
#
#       OPTIONS:  remove
#          BUGS:  ---
#         NOTES:  ---
#  DEPENDENCIES:  	
#        AUTHOR:  Samuel Weru, samweru@gmail.com
#       COMPANY:  UNDESA
#       VERSION:  ---
#       CREATED:  ---
#      REVISION:  ---
#===============================================================================

set -e

case "$1" in

abort-install)

		rm -rf /opt/bungeni/updates/$LATEST
	;;
	
remove|upgrade|failed-upgrade|abort-upgrade)
		
		echo "bungeni update successfully removed."
    ;;
*)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

exit 0
