#!/bin/sh
#===============================================================================
#
#          FILE:  postinst
#
#   DESCRIPTION:  Update post install script
#
#       OPTIONS:  configure
#          BUGS:  ---
#         NOTES:  ---
#  DEPENDENCIES:  	
#        AUTHOR:  Samuel Weru, samweru@gmail.com
#       COMPANY:  UNDESA
#       VERSION:  ---
#       CREATED:  ---
#      REVISION:  ---
#===============================================================================

set -e

case "$1" in
configure)
		
	export LATEST=$(ls /opt/bungeni/updates/latest | grep bungeni-update | cut -d'.' -f -2)
	
	echo "Changing latest folder update name"
	mv /opt/bungeni/updates/latest /opt/bungeni/updates/$LATEST
		
	#echo "Extracting from update archive"	
	#tar -C / -zxf /opt/bungeni/updates/$LATEST/$LATEST.tar.gz
	
	#echo "Creating latest update list"
	#cat /opt/bungeni/updates/$LATEST/common.list /opt/bungeni/updates/$LATEST/include.list > /var/lib/dpkg/info/$LATEST.list
	#find /opt/bungeni/updates/$LATEST/ >> /var/lib/dpkg/info/$LATEST.list
	
	#echo "Creating latest update md5sums"
	#for i in $(cat /var/lib/dpkg/info/$LATEST.list)
	#do 
		#if [ ! -d "$i" ]
		#then
			#echo $i >> /opt/bungeni/updates/$LATEST/files.list
		#fi
	#done
	
	#cat /opt/bungeni/updates/$LATEST/files.list | xargs md5sum > /var/lib/dpkg/info/$LATEST.md5sums
	
	###############################################
    # Start Postgresql, Do Upgrade, Stop Postgresql
    ###############################################
	# echo "Running db schema upgrade"
	# su bungeni -l -c "/opt/bungeni/bungeni_apps/postgres/bin/pg_ctl start -D /opt/bungeni/bungeni_apps/postgres-data/ -l /opt/bungeni/bungeni_apps/logs/postgres.log"
	# sleep 10
	# su bungeni -l -c "/opt/bungeni/bungeni_apps/bungeni/bin/alembic -c /opt/bungeni/bungeni_apps/bungeni/alembic.ini upgrade head"
	# su bungeni -l -c "/opt/bungeni/bungeni_apps/postgres/bin/pg_ctl stop -D /opt/bungeni/bungeni_apps/postgres-data/ -l /opt/bungeni/bungeni_apps/logs/postgres.log"
	
	#################################################################
    # Exist Update: Load new exist, restore data, Kill all bungeni ps
    #################################################################
	echo "Extracting from update archive"	
	rm -rf /opt/bungeni/bungeni_apps/exist
	tar -C /opt/bungeni/bungeni_apps -zxf /opt/bungeni/updates/$LATEST/exist_xmldb-17342.tar.gz
	mv /opt/bungeni/bungeni_apps/exist* /opt/bungeni/bungeni_apps/exist
	chown bungeni:bungeni -Rf /opt/bungeni/bungeni_apps/exist
	
	echo "Clean out any lock files"
    find /opt/bungeni/bungeni_apps/exist/webapp/WEB-INF/data -type f \( -name '*.lck' -o -name '*.lock' \) -exec rm -rf {} \;
	
	echo "Start new exist"	
	su bungeni -l -c "JAVA_HOME=$JAVA_HOME java -Xms128m -Xmx512m \
                -Dfile.encoding=UTF-8 \
                -Djava.endorsed.dirs=/opt/bungeni/bungeni_apps/exist/lib/endorse \
                -Dexist.home=/opt/bungeni/bungeni_apps/exist \
                -Djetty.port=8088 \
                -jar /opt/bungeni/bungeni_apps/exist/start.jar jetty" &
    
    sleep 11
    echo "Restore bungeni-xml"
    su bungeni -l -c "JAVA_HOME=$JAVA_HOME \ 
			java -jar -Dexist.home=/opt/bungeni/bungeni_apps/exist/ /opt/bungeni/bungeni_apps/exist/start.jar \
			backup -u admin -r /opt/bungeni/updates/$LATEST/db/bungeni-xml/__contents__.xml \
			-ouri=xmldb:exist://127.0.0.1:8088/exist/xmlrpc"
	
	echo "Restore bungeni-atts"
	su bungeni -l -c "JAVA_HOME=$JAVA_HOME \ 
			java -jar -Dexist.home=/opt/bungeni/bungeni_apps/exist/ /opt/bungeni/bungeni_apps/exist/start.jar \
			backup -u admin -r /opt/bungeni/updates/$LATEST/db/bungeni-atts/__contents__.xml \
			-ouri=xmldb:exist://127.0.0.1:8088/exist/xmlrpc"
	
	echo "Kill bungeni processes"
	pkill -u bungeni
	
    ;;
*)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

exit 0
