#!/bin/sh
#===============================================================================
#
#          FILE:  postinst
#
#   DESCRIPTION:  Update post install script
#
#       OPTIONS:  configure
#          BUGS:  ---
#         NOTES:  ---
#  DEPENDENCIES:  	
#        AUTHOR:  Samuel Weru, samweru@gmail.com
#       COMPANY:  UNDESA
#       VERSION:  ---
#       CREATED:  ---
#      REVISION:  ---
#===============================================================================

set -e

case "$1" in
configure)
		
	LATEST=$(ls /opt/bungeni/updates/latest | grep bungeni-update | cut -d'.' -f -2)
	
	echo "Changing latest folder update name"
	mv /opt/bungeni/updates/latest /opt/bungeni/updates/$LATEST
		
	echo "Extracting from update archive"	
	tar -C / -zxf /opt/bungeni/updates/$LATEST/$LATEST.tar.gz
	
	echo "Creating latest update list"
	cat /opt/bungeni/updates/$LATEST/common.list /opt/bungeni/updates/$LATEST/include.list > /var/lib/dpkg/info/$LATEST.list
	find /opt/bungeni/updates/$LATEST/ >> /var/lib/dpkg/info/$LATEST.list
	
	echo "Creating latest update md5sums"
	for i in $(cat /var/lib/dpkg/info/$LATEST.list)
	do 
		if [ ! -d "$i" ]
		then
			echo $i >> /opt/bungeni/updates/$LATEST/files.list
		fi
	done
	
	cat /opt/bungeni/updates/$LATEST/files.list | xargs md5sum > /var/lib/dpkg/info/$LATEST.md5sums
    ;;
*)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

exit 0
