#!/bin/sh
#===============================================================================
#
#          FILE:  preinst
#
#   DESCRIPTION:  Update preinstall script
#
#       OPTIONS:  install
#          BUGS:  ---
#         NOTES:  ---
#  DEPENDENCIES:  	
#        AUTHOR:  Samuel Weru, samweru@gmail.com
#       COMPANY:  UNDESA
#       VERSION:  ---
#       CREATED:  ---
#      REVISION:  ---
#===============================================================================

set -e

case "$1" in
install)
        
        mkdir -p /opt/bungeni/updates/latest 
        
        ############################
        # Postgresql Back Up 
        ############################
        # tar -czf postgres-data.tar.gz /opt/bungeni/bungeni_apps/postgres-data
        # mv postgres-data.tar.gz /opt/bungeni/updates/latest/
    ;;
*)

        echo "prerm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

exit 0
