/*
 * ODFTransfromPanel.java
 *
 * Created on October 9, 2007, 4:57 PM
 */

package org.bungeni.odtransform;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;

/**
 *
 * @author  Administrator
 */
public class ODFTransfromPanel extends javax.swing.JPanel {
    JFrame parent = null;
    /** Creates new form ODFTransfromPanel */
    public ODFTransfromPanel() {
        initComponents();
    }

     public ODFTransfromPanel(JFrame frame) {
        initComponents();
        parent = frame;

    }
       
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        txtODTDocument = new javax.swing.JTextField();
        btnSelectDoc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnTransform = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        btnSelectDoc.setText("Select ODT Document...");
        btnSelectDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectDocActionPerformed(evt);
            }
        });

        jLabel1.setText("<p>Select an ODT document below and Click the Transform button</p>");
        jLabel1.getAccessibleContext().setAccessibleName("");

        btnTransform.setText("Transform....");
        btnTransform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransformActionPerformed(evt);
            }
        });

        jButton1.setText("Close");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, txtODTDocument, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, btnSelectDoc, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 168, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(btnTransform, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 187, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 16, Short.MAX_VALUE)
                        .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 177, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 55, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(txtODTDocument, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnSelectDoc)
                .add(20, 20, 20)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(btnTransform))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTransformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransformActionPerformed
// TODO add your handling code here:
        String currentDirectory = "";
        String xsltFileName = "";
        String inputFileName = "content.xml";
        String inputODName = "";
        String outputFileName = "toString";
        try {
        currentDirectory = (new File(".")).getCanonicalPath();
        
        xsltFileName = currentDirectory + File.separator + "xslt"+ File.separator+ "ooo2akoma.xsl";
       
        inputODName = this.txtODTDocument.getText();
        
        org.bungeni.odtransform.ODTransform transformApp = new org.bungeni.odtransform.ODTransform(inputFileName,  inputODName, xsltFileName,  outputFileName ); 
	 try {
		transformApp.doTransform( );
                        
         } catch (Exception e) {
		System.out.println("Unable to transform");
		System.out.println(e.getMessage());
	   }
        
        
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnTransformActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
        parent.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
 private JFileChooser fc = new JFileChooser();
    private void btnSelectDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectDocActionPerformed
// TODO add your handling code here:
        int nReturnVal = fc.showOpenDialog(parent);
        if (nReturnVal == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            
            this.txtODTDocument.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_btnSelectDocActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSelectDoc;
    private javax.swing.JButton btnTransform;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtODTDocument;
    // End of variables declaration//GEN-END:variables
    
    public static void main(String[] args) {
          JFrame selectSectionDlg;
             selectSectionDlg = new JFrame();
             selectSectionDlg.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
             //initDebaterecord.setPreferredSize(new Dimension(420, 300));
             ODFTransfromPanel panel = new ODFTransfromPanel(selectSectionDlg);
             selectSectionDlg.getContentPane().add(panel);
             selectSectionDlg.setTitle("Transform ODT to AkomaNtoso");
             selectSectionDlg.pack();
             selectSectionDlg.setLocationRelativeTo(null);
             selectSectionDlg.setVisible(true);
             //selectSectionDlg.setAlwaysOnTop(true);  
         }
}
