#! /bin/bash -e

SUPERVISORD=/opt/bungeni/bungeni_apps/python27/bin/supervisord
PIDFILE=/opt/bungeni/bungeni_apps/pid/supervisord.pid
DAEMON_USER="bungeni"
OPTS="-c /opt/bungeni/bungeni_apps/config/supervisord.conf -u$DAEMON_USER"

test -x $SUPERVISORD || exit 0

. /lib/lsb/init-functions

export PATH="${PATH:+$PATH:}/usr/local/bin:/usr/sbin:/sbin"

case "$1" in
  start)
    log_begin_msg "Starting Supervisor daemon manager..."
    start-stop-daemon  --start --quiet --pidfile $PIDFILE -u$DAEMON_USER --exec $SUPERVISORD -- $OPTS || log_end_msg 1
    log_end_msg 0
    ;;
  stop)
    log_begin_msg "Stopping Supervisor daemon manager..."
    start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE  -u$DAEMON_USER || log_end_msg 1
    log_end_msg 0
    ;;

  restart|reload|force-reload)
    log_begin_msg "Restarting Supervisor daemon manager..."
    start-stop-daemon --stop -u$DAEMON_USER --quiet --oknodo --retry 30 --pidfile $PIDFILE
    start-stop-daemon --start -u$DAEMON_USER --quiet --pidfile $PIDFILE --exec $SUPERVISORD -- $OPTS || log_end_msg 1
    log_end_msg 0
    ;;

  *)
    log_success_msg "Usage: /etc/init.d/supervisor
{start|stop|reload|force-reload|restart}"
    exit 1
esac

exit 0

