from Products.Archetypes import atapi

SPECIAL_INTERESTS_LIST = atapi.DisplayList((
    ('women', 'Women Representative'),
    ('youth', 'Youth Representative'),
    ('disabled', 'Persons with disabilities'),
    ))


COUNTY_LIST = atapi.DisplayList((
    ('', ''),
    ('baringo', 'Baringo'),
    ('bomet', 'bomet'),    
    ('bungoma', 'Bungoma'),
    ('busia', 'Busia'),
    ('elgeyo_marakwet', 'Elgeyo/Marakwet'),
    ('embu', 'Embu'),
    ('garissa', 'Garissa'),
    ('homabay', 'Homa Bay'),
    ('isiolo', 'Isiolo'),
    ('kajiado', 'Kajiado'),
    ('kakamega', 'Kakamega'),
    ('kericho', 'Kericho'),
    ('kiambu', 'Kiambu'),
    ('kilifi', 'Kilifi'),
    ('kirinyaga', 'Kirinyaga'),
    ('kisii', 'Kisii'),
    ('kisumu', 'Kisumu'),
    ('kitui', 'Kitui'),
    ('kwale', 'Kwale'),
    ('laikipia', 'Laikipia'),
    ('lamu', 'Lamu'),
    ('machakos', 'Machakos'),
    ('makueni', 'Makueni'),
    ('mandera', 'Mandera'),
    ('marsabit', 'Marsabit'),
    ('meru', 'Meru'),
    ('migori', 'Migori'),
    ('mombasa', 'Mombasa'),
    ('muranga', 'Muranga'),
    ('nairobi', 'Nairobi'),
    ('nakuru', 'Nakuru'),
    ('nandi', 'Nandi'),
    ('narok', 'Narok'),
    ('nyamira', 'Nyamira'),
    ('nyandarua', 'Nyandarua'),
    ('nyeri', 'Nyeri'),
    ('samburu', 'Samburu'),
    ('siaya', 'Siaya'),
    ('taita_taveta', 'Taita Taveta'),
    ('tana_river', 'Tana River'),
    ('tharaka_nithi', 'Tharaka Nithi'),
    ('trans_nzoia', 'Trans Nzoia'),
    ('turkana', 'Turkana'),
    ('uasin_gishu', 'Uasin Gishu'),
    ('vihiga', 'Vihiga'),
    ('wajir', 'Wajir'),
    ('west_pokot', 'West Pokot'),
    ))



CONSTITUENCIES_LIST = {
    '' : ('',),
    'baringo' : ('Baringo East', 'Baringo Central', 'Baringo North', 'Eldama Ravine', 'Mogotio'),
    'bomet' : ('Bomet', 'Chepalungu', 'Sotik'),    
    'bungoma' : ('Mt. Elgon', 'Sirisia', 'Kabuchia', 'Bumula', 'Kandunyi', 'Webuye', 'Bokoli', 'Kimilili', 'Tongaren'),
    'busia' : ('Teso North', 'Teso South', 'Nambale', 'Matayos', 'Butula', 'Funyula', 'Budalangi'),
    'elgeyo_marakwet' : ('Marakwet East', 'Marakwet West', 'Keiyo East', 'Keiyo South'),
    'embu' : ('Manyatta', 'Runyenjes', 'Gachoka', 'Siakago'),    
    'garissa' : ('TaveDujis', 'Balambala', 'Lagdera', 'Dadaab', 'Fafi', 'Ijara'),
    'homabay' : ('Kasipul', 'Kabondo', 'Karachuonyo', 'Rangwe', 'Homabay Town', 'Ndhiwa', 'Mbita', 'Gwassi'),
    'isiolo' : ('Isiolo North', 'Isiolo South'),
    'kajiado' : ('Kajiado Central', 'Kajiado North', 'Kajiado South'),
    
    'kakamega' : ('Lugari', 'Likuyani', 'Malava', 'Lurambi', 'Makholo', 'Mumias', 'Mumias East', 'Matungu', 'Butere', 'Khwisero', 'Shinyalu', 'Ikolomani'),
    
    'kericho' : ('Ainamoi', 'Belgut', 'Kipkelion'),
    'kiambu' : ('Gatundu South', 'Gatundu North', 'Juja', 'Thika Town', 'Ruiru', 'Githunguri', 'Kiambu', 'Kiambaa', 'Kabete', 'Kikuyu', 'Limuru', 'Lari'),
    
    'kilifi' : ('Kilifi North', 'Kilifi South', 'Kaloleni', 'Rabai', 'Ganze', 'Malindi', 'Magarini'),
    'kirinyaga' : ('Mwea', 'Gichugu', 'Ndia', 'Kirinyaga Central'),
    'kisii' : ('Bonchari', 'South Mugirango', 'Bomachoge', 'Bobasi', 'Gucha', 'Nyaribari Masaba', 'Nyaribari Chache', 'Matrani', 'Mosocho'),
    'kisumu' : ('Kisumu East', 'Kisumu West', 'Kisumu Central', 'Seme', 'Nyando', 'Muhoroni', 'Nyakach'),
    'kitui' : ('Mwingi North', 'Mwingi Central', 'Mwingi South', 'Kitui West', 'Kitui Rural', 'Kitui Town', 'Mutitu', 'Kitui South'),
    'kwale' : ('Msambweni', 'Lunga Lunga', 'Matuga', 'Kinango'),
    'laikipia' : ('Laikipia East', 'Laikipia West', 'Laikipia North'),
    'lamu' : ('Lamu East', 'Lamu West'),
    'machakos' : ('Masinga', 'Yatta', 'Kangundo', 'Matungulu', 'Kathiani', 'Mavoko', 'Machakos Town', 'Mwala'),
    'makueni' : ('Mbooni', 'Kilome', 'Kaiti', 'Makueni', 'Kibwezi West', 'Kibwezi East'),
    'mandera' : ('Mandera West', 'Banisa', 'Mandera North', 'Mandera East', 'Lafey'),
    'marsabit' : ('Moyale', 'North Horr', 'Saku', 'Laisamis'),
    
    'meru' : ('Igembe South', 'Igembe Central', 'Igembe North', 'Tigania West', 'Tigania East', 'North Imenti', 'Buuri', 'Central Imenti', 'South Imenti'),
    
    'migori' : ('Rongo', 'Awendo', 'Migori East', 'Migori West', 'Uriri', 'Nyatike', 'Kuria East', 'Kuria West'),
    'mombasa' : ('Changamwe', 'Jomvu', 'Kisauni', 'Nyali', 'Likoni', 'Mvita', 'Kwale'),
    'muranga' : ('Kangema', 'Mathioya', 'Kiharu', 'Kigumo', 'Maragwa', 'Kandara', 'Gatanga'),
    
    'nairobi' : ('Westlands', 'Parklands', 'Dagoretti', 'Karen / Langata', 'Kibira', 'Roysambu', 'Kasarani', 'Ruaraka', 'Kariobangi', 'Kayole', 'Embakasi', 'Mihango', 'Nairobi West', 'Makadara', 'Kamukunji', 'Starehe', 'Mathare'),
    
    'nakuru' : ('Molo', 'Njoro', 'Naivasha', 'Gilgil', 'Kuresoi South', 'Kuresoi North', 'Subukia', 'Rongai', 'Bahati', 'Nakuru Town West', 'Nakuru Town East'),
    'nandi' : ('Tinderet', 'Aldai', 'Nandi Hills', 'Emgwen North', 'Emgwen South', 'Mosop'),
    'narok' : ('Kilgoris', 'Emurua Dikirr', 'Narok North', 'Kajiado East', 'Kajiado West'),
    'nyamira' : ('Kitutu Masaba', 'North Mugirango', 'West Mugirango'),
    'nyandarua' : ('Kinangop', 'Kipipiri', 'Ol-Kalou', 'Ol-Jorok', 'Ndaragwa'),
    'nyeri' : ('Tetu', 'Kieni', 'Mathira', 'Othaya', 'Mukuwe-ini', 'Nyeri Town'),
    'samburu' : ('Samburu West', 'Samburu North', 'Samburu East'),
    'siaya' : ('Ugenya', 'Ugunja', 'Alego Usonga', 'Gem', 'Bondo', 'Rarieda'),
    'taita_taveta' : ('Taveta', 'Wundanyi', 'Mwatate', 'Voi'),
    'tana_river' : ('Garsen', 'Galole', 'Bura'),
    'tharaka_nithi' : ('Nithi', 'Maara', 'Tharaka'),
    'trans_nzoia' : ('Kwanza', 'Endebess', 'Saboti', 'Kiminini', 'Cherenganyi'),
    'turkana' : ('Turkana North', 'Turkana West', 'Turkana Central', 'Loima', 'Turkana South', 'Turkana East'),
    'uasin_gishu' : ('Eldoret East', 'Eldoret North', 'Eldoret South'),
    'vihiga' : ('Vihiga', 'Sabatia', 'Hamisi', 'Emuhaya', 'Luanda'),
    'wajir' : ('Wajir North', 'Wajir East', 'Tarbaj', 'Wajir West', 'Eldas', 'Wajir South'),
    'west_pokot' : ('Kapenguri', 'Sigor', 'Kacheliba', 'Pokot South'),
    }
