/*
 * documentMetadataPanel.java
 *
 * Created on May 15, 2008, 11:47 AM
 */

package org.bungeni.editor.panels;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.Timer;
import org.bungeni.editor.metadata.DocumentMetadataTableModel;
import org.bungeni.ooo.OOComponentHelper;

/**
 *
 * @author  Administrator
 */
public class documentMetadataPanel extends javax.swing.JPanel {
    private OOComponentHelper ooDocument;
    private JFrame parentFrame;
    private DocumentMetadataTableModel docMetadataTableModel ;
    private Timer docMetadataTimer;
    /** Creates new form documentMetadataPanel */
    public documentMetadataPanel() {
        initComponents();
    }
    
   public documentMetadataPanel(OOComponentHelper ooDocument, JFrame parentFrame){
         this.parentFrame=parentFrame;
         this.ooDocument=ooDocument;
         init();
     }
    
    private void init() {
       initComponents();
       initTableDocumentMetadata();    
       initTimer();
    }
    

    
    private void initTableDocumentMetadata() {
        docMetadataTableModel = new DocumentMetadataTableModel(ooDocument);
        this.tableDocumentMetadata.setModel(docMetadataTableModel);
    }
    
     private synchronized void initTimer(){
          docMetadataTimer = new Timer(4000, new ActionListener() {
              public void actionPerformed(ActionEvent e) {
                refreshDocMetadataTable();
              }
           });
           docMetadataTimer.start();
    }
     
     private void refreshDocMetadataTable(){
        docMetadataTableModel.refreshMetaData();

     }
     
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        scrollTableDocumentMetadata = new javax.swing.JScrollPane();
        tableDocumentMetadata = new javax.swing.JTable();
        lblDescDocMetadata = new javax.swing.JLabel();

        getAccessibleContext().setAccessibleDescription("Doc Metadata");
        tableDocumentMetadata.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollTableDocumentMetadata.setViewportView(tableDocumentMetadata);

        lblDescDocMetadata.setText("Document Metadata");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblDescDocMetadata, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 196, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .add(scrollTableDocumentMetadata, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(lblDescDocMetadata)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(scrollTableDocumentMetadata, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 268, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDescDocMetadata;
    private javax.swing.JScrollPane scrollTableDocumentMetadata;
    private javax.swing.JTable tableDocumentMetadata;
    // End of variables declaration//GEN-END:variables
    
}
