#!/bin/sh

set -e

case "$1" in
    configure)

		echo "setting plone ownership to bungeni user"
		chown -R bungeni:bungeni /opt/bungeni/bungeni_apps/bungeni/plone
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
		exit 0
    ;;
    *)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 0
    ;;
esac

exit 0
