#!/bin/bash
#===============================================================================
#
#          FILE:  postinst
#
#
#   DESCRIPTION:  Bungeni postinstall script, Adds bungeni user and home registers service	
#
#       OPTIONS:  configure
#          BUGS:  ---
#         NOTES:  ---
#
#       AUTHORS:  Ashok Hariharan <ashok@parliaments.info>
#				  Samuel Weru <samweru@gmail.com>
#
#  ORGANIZATION:  UNDESA
#       VERSION:  ---
#       CREATED:  ---
#      REVISION:  ---
#===============================================================================

set -e

case "$1" in
configure)
		echo " Adding rabbitmq user " 
		/opt/bungeni/bungeni_apps/rabbitmq/sbin/rabbitmq-server -detached || true
		sleep 15
		/opt/bungeni/bungeni_apps/rabbitmq/sbin/rabbitmqctl add_user admin admin || true
		/opt/bungeni/bungeni_apps/rabbitmq/sbin/rabbitmqctl set_user_tags admin administrator || true
		/opt/bungeni/bungeni_apps/rabbitmq/sbin/rabbitmqctl set_permissions -p / admin ".*" ".*" ".*" || true
		/opt/bungeni/bungeni_apps/rabbitmq/sbin/rabbitmqctl delete_user guest || true
		/opt/bungeni/bungeni_apps/rabbitmq/sbin/rabbitmqctl stop_app || true
		/opt/bungeni/bungeni_apps/rabbitmq/sbin/rabbitmqctl stop || true
		echo "Adding bungeni group and user..."
		useradd bungeni
		echo "bungeni:bungeni" | chpasswd
		echo "Setting Permissions..."
		usermod -d /opt/bungeni bungeni
		usermod -s /bin/bash bungeni
		chown -R bungeni:bungeni /opt/bungeni
		update-rc.d bungeni_services defaults
    ;;
*)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

exit 0
