#!/bin/sh

set -e

case "$1" in
install)

	echo "Creating directory structure"
	mkdir -p /opt/bungeni/.bungenitmp
    ;;
*)

        echo "prerm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

exit 0
