#!/bin/sh -e
#===============================================================================
#
#          FILE:  postrm
#
#					
#
#       OPTIONS:  purge, remove, upgrade, failed-upgrade, abort-install, abort-upgrade, disappear
#          BUGS:  ---
#         NOTES:  ---
#
#       AUTHORS:  Ashok Hariharan <ashok@parliaments.info>
#				  Samuel Weru <samweru@gmail.com>
#
#  ORGANIZATION:  UNDESA
#       VERSION:  ---
#       CREATED:  ---
#      REVISION:  ---
#===============================================================================

case "$1" in
	purge)
    ;;
	remove|upgrade|failed-upgrade|abort-install|abort-upgrade)
    
		echo "PostgreSQL successfully removed."
    ;;
	disappear)
    ;;
	*)

        echo "prerm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

exit 0
