#!/bin/bash
#===============================================================================
#
#          FILE:  postinst
#
#
#   DESCRIPTION:  Postgresql postinstall script, sets ownership of postgres folder to bungeni user	
#
#       OPTIONS:  configure, abort-upgrade, abort-remove, abort-deconfigure
#          BUGS:  ---
#         NOTES:  ---
#
#       AUTHORS:  Ashok Hariharan <ashok@parliaments.info>
#				  Samuel Weru <samweru@gmail.com>
#
#  ORGANIZATION:  UNDESA
#       VERSION:  ---
#       CREATED:  ---
#      REVISION:  ---
#===============================================================================

set -e

case "$1" in
    configure)

		echo "setting postgresql ownership to bungeni user"
		chown -R bungeni:bungeni /opt/bungeni/bungeni_apps/postgres*
		
		echo "refresh dynamic link cache"
		echo "/opt/bungeni/bungeni_apps/postgres/lib/" > lib-bungeni-plone.conf
		mv lib-bungeni-plone.conf /etc/ld.so.conf.d/
		ldconfig
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
		exit 0
    ;;
    *)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 0
    ;;
esac

exit 0
