/*
 * SelectSection.java
 *
 * Created on October 3, 2007, 12:59 PM
 */

package org.bungeni.editor.selectors;

import com.sun.star.beans.UnknownPropertyException;
import com.sun.star.beans.XPropertySet;
import com.sun.star.container.NoSuchElementException;
import com.sun.star.lang.WrappedTargetException;
import com.sun.star.text.XTextSection;
import javax.swing.JDialog;
import javax.swing.WindowConstants;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import org.bungeni.ooo.OOComponentHelper;
import org.bungeni.ooo.ooQueryInterface;
import org.bungeni.utils.CommonTreeFunctions;
import org.bungeni.utils.MessageBox;

/**
 *
 * @author  Administrator
 */
public class SelectSection extends javax.swing.JPanel {
    OOComponentHelper ooDocument;
    
    private static org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger(SelectSection.class.getName());
    private DefaultMutableTreeNode sectionRootNode = null;
    private JDialog parent  = null;
    private String m_selectedSection = "";
    private String m_selectedActionCommand = "";
    private boolean emptyRootNode = false;
    private boolean cancelClicked = false;
    private SelectorDialogModes selectorMode;
    /** Creates new form SelectSection */
    public SelectSection() {
        initComponents();
    }
    
    public SelectSection(OOComponentHelper doc, JDialog parentDlg, SelectorDialogModes mode) {
        initComponents();
        this.ooDocument = doc;
        this.parent = parentDlg;
        this.selectorMode = mode;
        initSectionList();
    }
    
    
     private void initSectionList() {
         initSectionsArray();   
         treeSectionStructure.setModel(new DefaultTreeModel(sectionRootNode));
         CommonTreeFunctions.expandAll(treeSectionStructure, true);
      }
    
    private void initSectionsArray() {
        try {
            if (!ooDocument.isXComponentValid()) return;
            
            treeSectionStructure.removeAll();
            if (!ooDocument.getTextSections().hasByName("root")) {
                log.debug("no root section found");
                return;
            }
            Object rootSection = ooDocument.getTextSections().getByName("root");
            XTextSection theSection = ooQueryInterface.XTextSection(rootSection);
            if (theSection.getChildSections().length == 0) {
                //root is empty and has no children. 
                //set empty status 
                this.emptyRootNode = true;
            }
            sectionRootNode = new DefaultMutableTreeNode(new String("root"));
            
            recurseSections (theSection, sectionRootNode);
            
            CommonTreeFunctions.expandAll(treeSectionStructure, true);
        
        } catch (NoSuchElementException ex) {
            log.debug(ex.getMessage());
        } catch (WrappedTargetException ex) {
            log.debug(ex.getMessage());
        }
    }
    
    
    private void recurseSections (XTextSection theSection, DefaultMutableTreeNode node ) {
        try {
        //recurse children
        XTextSection[] sections = theSection.getChildSections();
        if (sections != null ) {
            if (sections.length > 0 ) {
                //start from last index and go to first
                for (int nSection = sections.length - 1 ; nSection >=0 ; nSection--) {
                    log.debug ("section name = "+sections[nSection] );
                    //get the name for the section and add it to the root node.
                    XPropertySet childSet = ooQueryInterface.XPropertySet(sections[nSection]);
                    String childSectionName = (String) childSet.getPropertyValue("LinkDisplayName");
                    DefaultMutableTreeNode newNode = new DefaultMutableTreeNode(childSectionName);
                    node.add(newNode);
                    recurseSections (sections[nSection], newNode);
                }
            } else 
                return;
        } else 
            return;
        } catch (UnknownPropertyException ex) {
            log.debug(ex.getMessage());
        } catch (WrappedTargetException ex ) {
            log.debug(ex.getMessage());
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        grpSelectSection = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeSectionStructure = new javax.swing.JTree();
        btnApply = new javax.swing.JButton();
        rbtnBefore = new javax.swing.JRadioButton();
        rbtnAfter = new javax.swing.JRadioButton();
        rbtnInside = new javax.swing.JRadioButton();
        lblMessage = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();

        jScrollPane1.setViewportView(treeSectionStructure);

        btnApply.setText("Apply");
        btnApply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApplyActionPerformed(evt);
            }
        });

        grpSelectSection.add(rbtnBefore);
        rbtnBefore.setSelected(true);
        rbtnBefore.setText("Before Section");
        rbtnBefore.setActionCommand("BEFORE_SECTION");
        rbtnBefore.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        rbtnBefore.setMargin(new java.awt.Insets(0, 0, 0, 0));

        grpSelectSection.add(rbtnAfter);
        rbtnAfter.setText("After Section");
        rbtnAfter.setActionCommand("AFTER_SECTION");
        rbtnAfter.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        rbtnAfter.setMargin(new java.awt.Insets(0, 0, 0, 0));

        grpSelectSection.add(rbtnInside);
        rbtnInside.setText("Inside Section");
        rbtnInside.setActionCommand("INSIDE_SECTION");
        rbtnInside.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        rbtnInside.setMargin(new java.awt.Insets(0, 0, 0, 0));

        lblMessage.setText("<html><p>Select a Section from the Tree on the left, \nand then select the position where you would like to \n add the new section.</p></html>");

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 228, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(14, 14, 14)
                        .add(lblMessage, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, rbtnInside, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, rbtnAfter, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, rbtnBefore, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .add(layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(btnCancel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(btnApply, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(lblMessage, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(rbtnBefore)
                        .add(17, 17, 17)
                        .add(rbtnAfter)
                        .add(17, 17, 17)
                        .add(rbtnInside)
                        .add(19, 19, 19)
                        .add(btnApply)
                        .add(13, 13, 13)
                        .add(btnCancel))
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 230, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
// TODO add your handling code here:
        cancelClicked = true;
        parent.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnApplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApplyActionPerformed
// TODO add your handling code here:
       TreePath selectionPath =  treeSectionStructure.getSelectionPath();
       if (selectionPath != null ) {
           DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) selectionPath.getLastPathComponent();
           m_selectedSection = (String) selectedNode.getUserObject();
           m_selectedActionCommand = grpSelectSection.getSelection().getActionCommand();
           parent.dispose();
           return;
       } else {
           MessageBox.OK(parent, "You must select a section!");
           return;
       }
    }//GEN-LAST:event_btnApplyActionPerformed
   
    public String getSelectedActionCommand() {
        return this.m_selectedActionCommand;
    }
    
    public String getSelectedSection() {
        return this.m_selectedSection;
    }
    
    public boolean isCancelClicked() {
        return cancelClicked;
    }
    public static boolean Launchable(OOComponentHelper ooDoc) {
        //launchable only when the root section has children
        if (ooDoc.getTextSections().getElementNames().length > 1 ) {
            if (ooDoc.getTextSections().hasByName("root")) {
                return true;
            } else {
                return false;
            }
        }
        return false;
    }
    
    public static JDialog Launch(OOComponentHelper ooDoc, SelectorDialogModes mode) {
          JDialog selectSectionDlg;
             selectSectionDlg = new JDialog();
             selectSectionDlg.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
             //initDebaterecord.setPreferredSize(new Dimension(420, 300));
             SelectSection panel = new SelectSection(ooDoc, 
                     selectSectionDlg, mode);
             selectSectionDlg.getContentPane().add(panel);
             selectSectionDlg.setTitle("Select Section");
             selectSectionDlg.pack();
             selectSectionDlg.setLocationRelativeTo(null);
             selectSectionDlg.setModal(true);
             selectSectionDlg.setVisible(true);
             selectSectionDlg.setAlwaysOnTop(true);  
             
             return selectSectionDlg;
    }
    
    public boolean isRootNodeEmpty() {
        return this.emptyRootNode;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnApply;
    private javax.swing.JButton btnCancel;
    private javax.swing.ButtonGroup grpSelectSection;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JRadioButton rbtnAfter;
    private javax.swing.JRadioButton rbtnBefore;
    private javax.swing.JRadioButton rbtnInside;
    private javax.swing.JTree treeSectionStructure;
    // End of variables declaration//GEN-END:variables
   
}
