load 'deploy' if respond_to?(:namespace) # cap2 differentiator
Dir['vendor/plugins/*/recipes/*.rb'].each { |plugin| load(plugin) }
load 'config/commonfunctions'
load 'config/bungeni_presetup'
load 'config/bungeniconfigvars'
load 'config/bungeniconfiglocalcache'
load 'config/bungeni_tasks'
load 'config/bungeni_update'
load 'config/bungeni_install'
load 'config/bungeni_services'
load 'config/deploy'
