#!/bin/sh

set -e

case "$1" in
remove)

		echo "bungeni exist-db update successfully removed."
    ;;
*)

        echo "prerm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

exit 0
