#!/bin/sh

set -e

case "$1" in
configure)

		echo "Removing bungeni existDb post remove scritpt"	
		rm /var/lib/dpkg/info/bungeni-exist-db.postrm
		echo "Renaming bungeni-exist-db-update.postrm-1 to bungeni-exist-db.postrm"
		mv /var/lib/dpkg/info/bungeni-exist-db-update.postrm-1 /var/lib/dpkg/info/bungeni-exist-db.postrm

		echo "Removing bungeni existDb preremove scritpt"	
		rm /var/lib/dpkg/info/bungeni-exist-db.prerm
		echo "Renaming bungeni-exist-db-update.prerm-1 to bungeni-exist-db.prerm"
		mv /var/lib/dpkg/info/bungeni-exist-db-update.prerm-1 /var/lib/dpkg/info/bungeni-exist-db.prerm
		
		chown root:root /var/lib/dpkg/info/bungeni*
		exit 0
    ;;
*)

        echo "prerm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

exit 0
