#!/bin/sh

set -e

echo "Removing exist db postremove script"
./var/lib/dpkg/info/bungeni-exist-db-update.postrm-1 install

echo "Removing exist db preremove script 1"
./var/lib/dpkg/info/bungeni-exist-db-update.prerm-1 install

exit 0
