#!/bin/bash
#===============================================================================
#
#          FILE:  postrm
#
#
#   DESCRIPTION:  Uninstalls the 1.20140730 update 
#
#       OPTIONS:  purge, remove, upgrade, failed-upgrade, abort-install, abort-upgrade, disappear
#          BUGS:  ---
#         NOTES:  ---
#
#       AUTHORS:  Ashok Hariharan <ashok@parliaments.info>
#
#       VERSION:  1.20140730
#       CREATED:  ---
#      REVISION:  ---
#===============================================================================

set -e

case "$1" in
    abort-install)
    echo "Failed while attempting to install update"
    exit 0
    ;;
    purge)
	
	echo "Removing installed varnish"
	rm -rf /opt/bungeni/bungeni_apps/varnish
    echo "Restoring earlier varnish folder"
    mv /opt/bungeni/bungeni_apps/varnish.bak.1.20140730 /opt/bungeni/bungeni_apps/varnish
    echo "Restoring earlier supervisor configuration"
    mv /opt/bungeni/bungeni_apps/config/supervisord.conf /opt/bungeni/bungeni_apps/config/supervisord.conf.uninst.1.20140730
    mv /opt/bungeni/bungeni_apps/config/supervisord.conf.bak.1.20140730 /opt/bungeni/bungeni_apps/config/supervisord.conf
    
    ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade)

    ;;
    disappear)
    ;;
    *)

        echo "prerm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

exit 0
