#!/bin/bash
#===============================================================================
#
#          FILE:  preinst
#
#
#   DESCRIPTION:  Creates bungeni temporary directory 		
#
#       OPTIONS:  install
#          BUGS:  ---
#         NOTES:  ---
#
#       AUTHORS:  Ashok Hariharan <ashok@parliaments.info>
#				  Samuel Weru <samweru@gmail.com>
#
#  ORGANIZATION:  UNDESA
#       VERSION:  ---
#       CREATED:  ---
#      REVISION:  ---
#===============================================================================

set -e

case "$1" in
install)

	echo "Stopping varnish"
    service bungeni_services stop  || true  
    echo "Backing up current varnish installation"
    if [ -d "/opt/bungeni/bungeni_apps/varnish" ]; then
        mv /opt/bungeni/bungeni_apps/varnish /opt/bungeni/bungeni_apps/varnish.bak.1.20140730
    fi
    cp /opt/bungeni/bungeni_apps/config/supervisord.conf /opt/bungeni/bungeni_apps/config/supervisord.conf.bak.1.20140730
    
    ;;
*)

        echo "prerm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

exit 0
