/*
 * BungeniValidatorService.idl
 *
 * Created on 16.01.2007 - 10:14:41
 *
 */

#ifndef __org_openoffice_bungenivalidator_BungeniValidatorService__
#define __org_openoffice_bungenivalidator_BungeniValidatorService__

#include "XBungeniValidator.idl"

/*

Service Object of Validator, this is the Object which will be initiated by 
StarBasic's createUnoService command

*/

module org { module openoffice { module bungenivalidator {
    service BungeniValidatorService : XBungeniValidator;
}; }; };

#endif
