#!/bin/bash
#===============================================================================
#
#          FILE:  inst_all.sh
#
#         USAGE:  ./inst_all.sh <dist release folder>
#
#   DESCRIPTION:  Install all the set of bungeni release debian packages
#
#       OPTIONS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Samuel Weru, samweru@gmail.com
#  ORGANIZATION:  UNDESA
#       VERSION:  ---
#       CREATED:  ---
#      REVISION:  ---
#===============================================================================

cd $1
for f in *.deb; do yes y | sudo gdebi $f; done
