/*
 * InitDebateRecord.java
 *
 * Created on August 27, 2007, 11:39 AM
 */

package org.bungeni.editor.dialogs;

import com.sun.star.text.XText;
import com.sun.star.text.XTextContent;
import com.sun.star.text.XTextCursor;
import com.sun.star.text.XTextViewCursor;
import java.awt.Container;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JRootPane;
import org.bungeni.db.DefaultInstanceFactory;
import org.bungeni.db.toolbarAction;
import org.bungeni.editor.BungeniEditorProperties;
import org.bungeni.editor.fragments.FragmentsFactory;
import org.bungeni.editor.macro.ExternalMacro;
import org.bungeni.editor.macro.ExternalMacroFactory;
import org.bungeni.ooo.OOComponentHelper;

/**
 *
 * @author  Administrator
 * This class creates the initial MastHead section
 * - creates text section with specific name
 * - allows setting various variables within that section
 * - slaps the text into the created text section
 */
public class InitDebateRecord extends javax.swing.JPanel {
    private OOComponentHelper ooDocument;
    private JDialog parent;
    private toolbarAction theAction;
   private static org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger(InitDebateRecord.class.getName());
     
   private String m_strLogoPath; 
   private String m_strLogoFileName;
    /** Creates new form InitDebateRecord */
    public InitDebateRecord() {
        initComponents();
    }
    
    public InitDebateRecord(OOComponentHelper ooDocument, JDialog parentDlg, toolbarAction theAction) {
        this.ooDocument = ooDocument;
        this.parent = parentDlg;
        this.theAction = theAction;
        initComponents();
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        initdebate_debatedate = new org.jdesktop.swingx.JXDatePicker();
        lbl_initdebate_hansarddate = new javax.swing.JLabel();
        lbl_initdate_mastheadlogo = new javax.swing.JLabel();
        btn_initdebate_selectlogo = new javax.swing.JButton();
        initdebate_timeofhansard = new javax.swing.JTextField();
        lbl_initdebate_hansardtime = new javax.swing.JLabel();
        btn_initdebate_apply = new javax.swing.JButton();
        btn_initdebate_cancel = new javax.swing.JButton();
        lbl_initdebate_setpath = new javax.swing.JLabel();

        lbl_initdebate_hansarddate.setText("Hansard Date");

        lbl_initdate_mastheadlogo.setText("Masthead Logo");

        btn_initdebate_selectlogo.setText("Select Logo...");
        btn_initdebate_selectlogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_initdebate_selectlogoActionPerformed(evt);
            }
        });

        lbl_initdebate_hansardtime.setText("Hansard Time");

        btn_initdebate_apply.setText("Apply to Document ");
        btn_initdebate_apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_initdebate_applyActionPerformed(evt);
            }
        });

        btn_initdebate_cancel.setText("Cancel");
        btn_initdebate_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_initdebate_cancelActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(lbl_initdebate_setpath, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(lbl_initdebate_hansarddate, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, btn_initdebate_selectlogo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 133, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, lbl_initdate_mastheadlogo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, lbl_initdebate_hansardtime, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, btn_initdebate_apply, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 138, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btn_initdebate_cancel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, initdebate_debatedate, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
                            .add(initdebate_timeofhansard, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(36, 36, 36)
                .add(lbl_initdebate_hansarddate)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(initdebate_debatedate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lbl_initdebate_hansardtime)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(initdebate_timeofhansard, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lbl_initdate_mastheadlogo)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btn_initdebate_selectlogo)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lbl_initdebate_setpath, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 14, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btn_initdebate_apply)
                    .add(btn_initdebate_cancel))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_initdebate_applyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_initdebate_applyActionPerformed
// TODO add your handling code here:
        //get field values : 
    String strDebateDate = "", strTimeOfHansard = "", strLogoPath = "";   
    Date dtDebate = initdebate_debatedate.getDate();
    strTimeOfHansard =  initdebate_timeofhansard.getText();
    SimpleDateFormat formatter = new SimpleDateFormat ("MMMM dd yyyy");
    strDebateDate = formatter.format(dtDebate);
    strLogoPath = m_strLogoPath;
    //adding section
   if (theAction.action_type.equals("section")) {
        //create a text section
        //load the related document
        //set the field values in loaded document
           String sectionClass = "com.sun.star.text.TextSection";
           XTextViewCursor xCursor = ooDocument.getViewCursor();
           XText xText = xCursor.getText();
           XTextContent xSectionContent = ooDocument.createTextSection(theAction.action_naming_convention(), (short)1);
            try {
             xText.insertTextContent(xCursor, xSectionContent , true);
            } catch (com.sun.star.lang.IllegalArgumentException ex) {
            log.debug("in addTextSection : "+ex.getLocalizedMessage(), ex);
            } 
           
            //embed logo image
             ExternalMacro addImageIntoSection = ExternalMacroFactory.getMacroDefinition("AddImageIntoSection");
             addImageIntoSection.addParameter(theAction.action_naming_convention());
             addImageIntoSection.addParameter(m_strLogoPath);
             ooDocument.executeMacro(addImageIntoSection.toString(), addImageIntoSection.getParams());
            
            //loading the related document
            ExternalMacro insertDocIntoSection = ExternalMacroFactory.getMacroDefinition("InsertDocumentIntoSection");
            insertDocIntoSection.addParameter(theAction.action_naming_convention())   ;
            insertDocIntoSection.addParameter(FragmentsFactory.getFragment("hansard_masthead"));
            ooDocument.executeMacro(insertDocIntoSection.toString(), insertDocIntoSection.getParams());
            
            //set values from loaded document
            ExternalMacro setFieldValue = ExternalMacroFactory.getMacroDefinition("SetInputFieldValue");
            setFieldValue.addParameter(new String("debaterecord_official_date"));
            setFieldValue.addParameter(strDebateDate);
            ooDocument.executeMacro( setFieldValue.toString(),  setFieldValue.getParams());
   }       
    //ooDocument.executeDispatch("")
        //added Section, now execute Macros
        //load template document into main document
    /*
 
      
      ExternalMacro addTextToSection = ExternalMacroFactory.getMacroDefinition("AddTextToSection");
      addTextToSection.addParameter(new String("prayers"));
      addTextToSection.addParameter(new String ("National Assembly"));
      addTextToSection.addParameter(new String("Heading 1"));
    */
   
      
    }//GEN-LAST:event_btn_initdebate_applyActionPerformed

    private void btn_initdebate_selectlogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_initdebate_selectlogoActionPerformed
// TODO add your handling code here:
        String logoPath = "";
        logoPath = BungeniEditorProperties.getEditorProperty("logoPath");
        log.debug("logo path = " + logoPath);
        String strPath = DefaultInstanceFactory.DEFAULT_INSTALLATION_PATH();
        logoPath = strPath + File.separator + logoPath;
        log.debug("logo path new = "+ logoPath);
        JFileChooser chooser = new JFileChooser();
        File fLogoPath = new File(logoPath);
        chooser.setCurrentDirectory(fLogoPath);
        int nReturnVal = chooser.showOpenDialog(this);
        if (nReturnVal == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
            m_strLogoFileName = file.getName();
            m_strLogoPath = file.getAbsolutePath();
            lbl_initdebate_setpath.setText(m_strLogoFileName);
            //This is where a real application would open the file.
            log.debug("Opening: " + file.getName() + "." + "\n");
        } else {
            log.debug("Open command cancelled by user." + "\n");
        }
    }//GEN-LAST:event_btn_initdebate_selectlogoActionPerformed

    private void btn_initdebate_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_initdebate_cancelActionPerformed
// TODO add your handling code here:
        parent.dispose();
    }//GEN-LAST:event_btn_initdebate_cancelActionPerformed
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_initdebate_apply;
    private javax.swing.JButton btn_initdebate_cancel;
    private javax.swing.JButton btn_initdebate_selectlogo;
    private org.jdesktop.swingx.JXDatePicker initdebate_debatedate;
    private javax.swing.JTextField initdebate_timeofhansard;
    private javax.swing.JLabel lbl_initdate_mastheadlogo;
    private javax.swing.JLabel lbl_initdebate_hansarddate;
    private javax.swing.JLabel lbl_initdebate_hansardtime;
    private javax.swing.JLabel lbl_initdebate_setpath;
    // End of variables declaration//GEN-END:variables
    
}
