/*
 * sectionPanel.java
 *
 * Created on July 23, 2007, 4:04 PM
 */

package org.bungeni.editor.panels;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.border.Border;
import org.bungeni.editor.dialogs.editorTabbedPanel;
import org.bungeni.ooo.OOComponentHelper;
import org.bungeni.editor.panels.ICollapsiblePanel;
/**
 *
 * @author  Administrator
 */
public class sectionPanel extends javax.swing.JPanel implements ICollapsiblePanel , ActionListener  {
   
    private static org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger(sectionPanel.class.getName());
    private OOComponentHelper ooDocument;

    /** Creates new form sectionPanel */
    public sectionPanel() {
        initComponents();
        initButtons();
    }
    
    /*
    public sectionPanel(OOComponentHelper ooDoc) {
      initComponents();
      initButtons();
      this.ooDocument = ooDoc;
    }
    */
    
    private void initButtons(){
        //reset toolbar
        //Border contentBorder = BorderFactory.createEmptyBorder(6, 8, 6, 8);
        // the control pane
        toolbarSectionButtons.setFloatable(false);
        //toolbarSectionButtons.setBorder(contentBorder);
        toolbarSectionButtons.setRollover(true);
        toolbarSectionButtons.setOpaque(false);
        JButton btnSectionPrayer = createButton("icon_01", "makePrayerSection", "Create a Prayer Section", "Prayer");
        toolbarSectionButtons.add(btnSectionPrayer);
        JButton btnSectionPaper = createButton("icon_02", "makePaperSection", "Create a Paper Section", "Paper");
        toolbarSectionButtons.add(btnSectionPaper);
        JButton btnNoticeOfMotion = createButton("icon_03", "makeNoticeOfMotionSection", "Create a Notice-of-Motion Section", "Notice of Motion");
        toolbarSectionButtons.add(btnNoticeOfMotion);
        JButton btnQuestionAnswerSection = createButton("icon_04", "makeQASection", "Create a Question-Answer Section", "Question Answer Section");
        toolbarSectionButtons.add(btnQuestionAnswerSection);
        JButton btnQuestionBlockSection = createButton("icon_05", "makeQuestionBlockSection", "Create a Question-Block Section", "Question Answer Section");
        toolbarSectionButtons.add(btnQuestionBlockSection);
        
    }
    
    private JButton createButton(String imageName, String actionCommand, String tooltipText, String altText){
           String imgLocation = "/gui/"
                             + imageName
                             + ".png";
            URL imageURL = sectionPanel.class.getResource(imgLocation);
        //Create and initialize the button.
        JButton button = new JButton();
        button.setActionCommand(actionCommand);
        button.setToolTipText(tooltipText);
        button.addActionListener(this);

        if (imageURL != null) {                      //image found
            button.setIcon(new ImageIcon(imageURL, altText));
        } else {                                     //no image found
            button.setText(altText);
           log.debug("Resource not found: "
                               + imgLocation);
        }
        return button;
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        toolbarSectionButtons = new javax.swing.JToolBar();

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(toolbarSectionButtons, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 216, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(toolbarSectionButtons, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 48, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void actionPerformed(ActionEvent e) {
        String cmd = e.getActionCommand() ;
        log.debug("action perfomed = "+ cmd);
        ItoolbarButtonEvent iEvent = getEventClass(cmd);
        
        iEvent.doCommand(this.ooDocument, cmd);
    }
    
    public ItoolbarButtonEvent getEventClass(String cmd){
        log.debug("getting command factory ....");
        ItoolbarButtonEvent event = toolbarButtonCommandFactory.getButtonEventHandler(cmd);
        return event;
    }

    public void setOOComponentHandle(OOComponentHelper ooComponent) {
        this.ooDocument = ooComponent;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar toolbarSectionButtons;
    // End of variables declaration//GEN-END:variables
    
}
