/*
 * textmarkupPanel.java
 *
 * Created on July 31, 2007, 3:12 PM
 */

package org.bungeni.editor.panels;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import org.bungeni.ooo.OOComponentHelper;

/**
 *
 * @author  Administrator
 */
public class textmarkupPanel extends javax.swing.JPanel implements ICollapsiblePanel, ActionListener {
    private OOComponentHelper ooDocument;
    private static org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger(sectionPanel.class.getName());
    
    /** Creates new form textmarkupPanel */
    public textmarkupPanel() {
        initComponents();
        log.debug("textmarkupPanel class was initialized...");
    }
    
    private void initButtons(){
        toolbarMarkupButtons.setFloatable(false);
        toolbarMarkupButtons.setRollover(true);
        toolbarMarkupButtons.setOpaque(false);
     
        toolbarMarkupButtons.add(createButton("icon_06", "makePrayerMarkup", "Mark selected text as Prayer", "Prayer"));
        toolbarMarkupButtons.add(createButton("icon_07", "makePaperMarkup", "Mark the selected text Paper Markup", "Paper"));
        toolbarMarkupButtons.add(createButton("icon_08", "makeNoticeOfMotionSection", "Create a Notice-of-Motion Section", "Notice of Motion"));
        toolbarMarkupButtons.add(createButton("icon_09", "makeQASection", "Create a Question-Answer Section", "Question Answer Section"));
        toolbarMarkupButtons.add(createButton("icon_10", "makeQuestionBlockSection", "Create a Question-Block Section", "Question Answer Section"));
        
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        toolbarMarkupButtons = new javax.swing.JToolBar();

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(toolbarMarkupButtons, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(toolbarMarkupButtons, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setOOComponentHandle(OOComponentHelper ooComponent) {
        this.ooDocument = ooComponent;
    }

    public void actionPerformed(ActionEvent e) {
    }
    
    private JButton createButton(String imageName, String actionCommand, String tooltipText, String altText){
           String imgLocation = "/gui/"
                             + imageName
                             + ".png";
            URL imageURL = sectionPanel.class.getResource(imgLocation);
        //Create and initialize the button.
        JButton button = new JButton();
        button.setActionCommand(actionCommand);
        button.setToolTipText(tooltipText);
        button.addActionListener(this);

        if (imageURL != null) {                      //image found
            button.setIcon(new ImageIcon(imageURL, altText));
        } else {                                     //no image found
            button.setText(altText);
           log.debug("Resource not found: "
                               + imgLocation);
        }
        return button;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar toolbarMarkupButtons;
    // End of variables declaration//GEN-END:variables
    
}
