/*
 * textmarkupPanel.java
 *
 * Created on July 31, 2007, 3:12 PM
 */

package org.bungeni.editor.panels;

import java.awt.Component;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import org.bungeni.ooo.OOComponentHelper;

/**
 *
 * @author  Administrator
 */
public class textmarkupPanel extends javax.swing.JPanel implements ICollapsiblePanel, ActionListener {
    private OOComponentHelper ooDocument;
    private static org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger(sectionPanel.class.getName());
    
    /** Creates new form textmarkupPanel */
    public textmarkupPanel() {
        initComponents();
        initButtons();
        log.debug("textmarkupPanel class was initialized...");
    }
    
    private void initButtons(){ 
        toolbarMarkupButtons.setLayout(new GridLayout(0, 2));
        toolbarMarkupButtons.setFloatable(false);
        toolbarMarkupButtons.setRollover(true);
        toolbarMarkupButtons.setOpaque(false);
        toolbarMarkupButtons.add(createButton("icon_06", "makePrayerMarkup", "Mark selected text as Prayer", "Prayer"));
        toolbarMarkupButtons.add(createButton("icon_07", "makePaperMarkup", "Mark the selected text Paper Markup", "Paper"));
        toolbarMarkupButtons.add(createButton("icon_08", "makePaperDetailsMarkup", "Mark the selected text as Paper Details", "Paper Details"));
        toolbarMarkupButtons.add(createButton("icon_09", "makeNoticeOfMotionMarkup", "Mark the selected text as Notice of Motion", "Notice of Motion"));
        toolbarMarkupButtons.add(createButton("icon_10", "makeNoticeMarkup", "Mark the selected text as Notice", "Question Answer Section"));
        toolbarMarkupButtons.add(createButton("icon_11", "makeNoticeDetailsMarkup", "Mark the selected text as Notice Details", "Question Answer Section"));
        toolbarMarkupButtons.add(createButton("icon_12", "makeQAMarkup", "Mark the selected text as QA", "Question Answer Section"));
        toolbarMarkupButtons.add(createButton("icon_13", "makeAgendaMarkup", "Mark the selected text as Agenda", "Question Answer Section"));
        toolbarMarkupButtons.add(createButton("icon_14", "makeQuestionMarkup", "Mark the selected text as Question", "Question Answer Section"));
        toolbarMarkupButtons.add(createButton("icon_15", "makeSpeechMarkup", "Mark the selected text as Speech", "Question Answer Section"));
            
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        toolbarMarkupButtons = new javax.swing.JToolBar();

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(toolbarMarkupButtons, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 216, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(toolbarMarkupButtons, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setOOComponentHandle(OOComponentHelper ooComponent) {
        this.ooDocument = ooComponent;
    }

    public void actionPerformed(ActionEvent e) {
        
        String cmd = e.getActionCommand() ;
        log.debug("action perfomed = "+ cmd);
        ItoolbarButtonEvent iEvent = getEventClass(cmd);
        
        iEvent.doCommand(this.ooDocument, cmd);
    }
    
    private JButton createButton(String imageName, String actionCommand, String tooltipText, String altText){
           String imgLocation = "/gui/"
                             + imageName
                             + ".png";
            URL imageURL = textmarkupPanel.class.getResource(imgLocation);
        //Create and initialize the button.
        JButton button = new JButton();
        button.setActionCommand(actionCommand);
        button.setToolTipText(tooltipText);
        button.addActionListener(this);

        if (imageURL != null) {                      //image found
            button.setIcon(new ImageIcon(imageURL, altText));
            //button.setText(altText);
            //button.setText(altText);
        } else {                                     //no image found
            button.setText(altText);
           log.debug("Resource not found: "
                               + imgLocation);
        }
        return button;
    }

    public Component getObjectHandle() {
        return this;
    }

    public ItoolbarButtonEvent getEventClass(String btnCommand) {
        log.debug("getting event class");
        ItoolbarButtonEvent event = toolbarButtonCommandFactory.getButtonEventHandler(btnCommand);
        return event;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToolBar toolbarMarkupButtons;
    // End of variables declaration//GEN-END:variables
    
}
