/*
 * frameBrokenReferences.java
 *
 * Created on May 25, 2008, 10:25 AM
 */

package org.bungeni.editor.panels.loadable;

import com.sun.star.beans.UnknownPropertyException;
import com.sun.star.lang.WrappedTargetException;
import com.sun.star.text.XTextField;
import com.sun.star.uno.AnyConverter;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.table.AbstractTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.TreeModel;
import javax.swing.tree.TreePath;
import org.bungeni.editor.providers.DocumentSectionTreeModelProvider;
import org.bungeni.ooo.OOComponentHelper;
import org.bungeni.utils.BungeniBNode;
import org.bungeni.utils.CommonTreeFunctions;
import org.bungeni.utils.MessageBox;

/**
 *
 * @author  Administrator
 */
public class frameBrokenReferences extends javax.swing.JFrame {
    private OOComponentHelper ooDocument;
    private ArrayList<XTextField> orphanedReferences;
    private JFrame parentFrame;
    private boolean launchedState = false;
    private static org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger(frameBrokenReferences.class.getName());

    /** Creates new form frameBrokenReferences */
    public frameBrokenReferences() {
        initComponents();
    }
    
    public frameBrokenReferences(OOComponentHelper ooDoc, JFrame parentFrame, ArrayList<XTextField> brokenReferences){
        setOOComponentHelper(ooDoc);
        setOrphanedReferences(brokenReferences);
        setParentFrame(parentFrame);
        init();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        taskpaneBrokenReferences = new com.l2fprod.common.swing.JTaskPane();
        taskpaneGrpFindBrokenReferences = new com.l2fprod.common.swing.JTaskPaneGroup();
        panelBrowseBrokenReferences = new javax.swing.JPanel();
        scrollBrowseBrokenReferences = new javax.swing.JScrollPane();
        tblBrowseBrokenReferences = new javax.swing.JTable();
        scrollMessageArea = new javax.swing.JScrollPane();
        txtMessageArea = new javax.swing.JTextArea();
        btnFindBroken = new javax.swing.JButton();
        btnFixBroken = new javax.swing.JButton();
        btnClose1 = new javax.swing.JButton();
        taskpaneGrpFixBrokenReferences = new com.l2fprod.common.swing.JTaskPaneGroup();
        panelFixBrokenReferences = new javax.swing.JPanel();
        scrollFixBrokenReferences = new javax.swing.JScrollPane();
        treeFixBrokenReferences = new javax.swing.JTree();
        btnFixBrokenReferences = new javax.swing.JButton();
        btnCloseFrame = new javax.swing.JButton();
        btnClose2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        taskpaneGrpFindBrokenReferences.setCollapsable(false);
        taskpaneGrpFindBrokenReferences.setTitle("Find Broken References");
        tblBrowseBrokenReferences.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollBrowseBrokenReferences.setViewportView(tblBrowseBrokenReferences);

        txtMessageArea.setColumns(20);
        txtMessageArea.setLineWrap(true);
        txtMessageArea.setRows(5);
        scrollMessageArea.setViewportView(txtMessageArea);

        btnFindBroken.setText("Find Broken");

        btnFixBroken.setText("Fix References");
        btnFixBroken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFixBrokenActionPerformed(evt);
            }
        });

        btnClose1.setText("Close");

        org.jdesktop.layout.GroupLayout panelBrowseBrokenReferencesLayout = new org.jdesktop.layout.GroupLayout(panelBrowseBrokenReferences);
        panelBrowseBrokenReferences.setLayout(panelBrowseBrokenReferencesLayout);
        panelBrowseBrokenReferencesLayout.setHorizontalGroup(
            panelBrowseBrokenReferencesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelBrowseBrokenReferencesLayout.createSequentialGroup()
                .addContainerGap()
                .add(panelBrowseBrokenReferencesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(panelBrowseBrokenReferencesLayout.createSequentialGroup()
                        .add(btnFindBroken, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 138, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnFixBroken, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 123, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnClose1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                    .add(scrollBrowseBrokenReferences, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
                    .add(scrollMessageArea, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE))
                .add(15, 15, 15))
        );
        panelBrowseBrokenReferencesLayout.setVerticalGroup(
            panelBrowseBrokenReferencesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelBrowseBrokenReferencesLayout.createSequentialGroup()
                .add(scrollMessageArea, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 83, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(scrollBrowseBrokenReferences, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 112, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 13, Short.MAX_VALUE)
                .add(panelBrowseBrokenReferencesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnFindBroken)
                    .add(btnFixBroken)
                    .add(btnClose1))
                .addContainerGap())
        );
        taskpaneGrpFindBrokenReferences.getContentPane().add(panelBrowseBrokenReferences);

        taskpaneBrokenReferences.add(taskpaneGrpFindBrokenReferences);

        taskpaneGrpFixBrokenReferences.setTitle("Fix Broken References");
        scrollFixBrokenReferences.setViewportView(treeFixBrokenReferences);

        btnFixBrokenReferences.setText("Insert Cross Ref");
        btnFixBrokenReferences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFixBrokenReferencesActionPerformed(evt);
            }
        });

        btnCloseFrame.setText("Browse Broken ");
        btnCloseFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseFrameActionPerformed(evt);
            }
        });

        btnClose2.setText("Close");

        org.jdesktop.layout.GroupLayout panelFixBrokenReferencesLayout = new org.jdesktop.layout.GroupLayout(panelFixBrokenReferences);
        panelFixBrokenReferences.setLayout(panelFixBrokenReferencesLayout);
        panelFixBrokenReferencesLayout.setHorizontalGroup(
            panelFixBrokenReferencesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(panelFixBrokenReferencesLayout.createSequentialGroup()
                .addContainerGap()
                .add(panelFixBrokenReferencesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(panelFixBrokenReferencesLayout.createSequentialGroup()
                        .add(btnFixBrokenReferences, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 138, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnCloseFrame, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnClose2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE))
                    .add(scrollFixBrokenReferences, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 412, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelFixBrokenReferencesLayout.setVerticalGroup(
            panelFixBrokenReferencesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, panelFixBrokenReferencesLayout.createSequentialGroup()
                .addContainerGap()
                .add(scrollFixBrokenReferences, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(panelFixBrokenReferencesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnFixBrokenReferences)
                    .add(btnClose2)
                    .add(btnCloseFrame))
                .addContainerGap())
        );
        taskpaneGrpFixBrokenReferences.getContentPane().add(panelFixBrokenReferences);

        taskpaneBrokenReferences.add(taskpaneGrpFixBrokenReferences);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(taskpaneBrokenReferences, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(taskpaneBrokenReferences, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFixBrokenReferencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFixBrokenReferencesActionPerformed
// TODO add your handling code here:
        applyInsertCrossReference();
    }//GEN-LAST:event_btnFixBrokenReferencesActionPerformed

    private void btnCloseFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseFrameActionPerformed
// TODO add your handling code here:
        this.taskpaneGrpFixBrokenReferences.setExpanded(false);
        this.taskpaneGrpFindBrokenReferences.setExpanded(true);
        
    }//GEN-LAST:event_btnCloseFrameActionPerformed

    private void btnFixBrokenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFixBrokenActionPerformed
// TODO add your handling code here:
        this.taskpaneGrpFindBrokenReferences.setExpanded(false);
        this.taskpaneGrpFixBrokenReferences.setExpanded(true);
    }//GEN-LAST:event_btnFixBrokenActionPerformed
    
    public void findBrokenFrameSetExpanded (boolean bState) {
        this.taskpaneGrpFindBrokenReferences.setExpanded(bState);
        this.taskpaneGrpFixBrokenReferences.setExpanded(!bState);
    }
    
    public void fixBrokenFrameSetExpanded (boolean bState) {
           this.taskpaneGrpFixBrokenReferences.setExpanded(bState);
           this.taskpaneGrpFindBrokenReferences.setExpanded(!bState);
    }
    
    public static frameBrokenReferences Launch(OOComponentHelper ooDoc, JFrame parentFrame, ArrayList<XTextField> brokenReferences){
                frameBrokenReferences f = new frameBrokenReferences( ooDoc,  parentFrame,  brokenReferences);
                f.setAlwaysOnTop(true);
                f.setSize(new Dimension(498, 380));
                f.setVisible(true);
                return f;
    }
        
    public static frameBrokenReferences Launch2(OOComponentHelper ooDoc, JFrame parentFrame, ArrayList<XTextField> brokenReferences){
                frameBrokenReferences f = new frameBrokenReferences( ooDoc,  parentFrame,  brokenReferences);
                f.setAlwaysOnTop(true);
                f.setSize(new Dimension(498, 380));
                f.fixBrokenFrameSetExpanded(true);
                f.setVisible(true);
                return f;
    }
    
    private void applyInsertCrossReference(){
        TreePath selectedPath = this.treeFixBrokenReferences.getSelectionPath();
        if (selectedPath != null) {
            DefaultMutableTreeNode selectedNode = (DefaultMutableTreeNode) selectedPath.getLastPathComponent();
            BungeniBNode thenode = (BungeniBNode) selectedNode.getUserObject();
            MessageBox.OK(this, thenode.getName());
        } else {
            MessageBox.OK(this, "Please select a section in the tree to insert a cross reference to it");
            return;
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frameBrokenReferences f = new frameBrokenReferences();
                f.setSize(new Dimension(498, 380));
                f.setVisible(true);
            }
        });
    }

    public void setOOComponentHelper(OOComponentHelper ooDoc) {
        this.ooDocument = ooDoc;
    }

    public void setOrphanedReferences(ArrayList<XTextField> brokenReferences) {
        this.orphanedReferences = brokenReferences;
    }

    public void setParentFrame(JFrame parentFrame) {
        this.parentFrame = parentFrame;
    }

    public boolean getLaunchedState(){
        return launchedState;
    }
    private void init() {
        initComponents();
        launchedState = true;
        this.txtMessageArea.setText("Broken references are listed below, double clicking on a reference will take you " +
                "to the point in the the document where the broken reference appears, Use the 'fix reference' option to repair the reference ");
        BrokenReferencesTableModel model = new BrokenReferencesTableModel(this.ooDocument, this.orphanedReferences);
        this.tblBrowseBrokenReferences.setModel(model);
        this.treeFixBrokenReferences.setModel(DocumentSectionTreeModelProvider.create_non_refreshing_treemodel());
        CommonTreeFunctions.expandAll(treeFixBrokenReferences);
        this.btnClose1.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e) {
              shutdownFrame();
            }
            
        });
        this.btnClose2.addActionListener(new ActionListener(){
            public void actionPerformed(ActionEvent e) {
               shutdownFrame();
            }
            
        });
    }
    
    private void shutdownFrame() {
        launchedState = false;
        dispose();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose1;
    private javax.swing.JButton btnClose2;
    private javax.swing.JButton btnCloseFrame;
    private javax.swing.JButton btnFindBroken;
    private javax.swing.JButton btnFixBroken;
    private javax.swing.JButton btnFixBrokenReferences;
    private javax.swing.JPanel panelBrowseBrokenReferences;
    private javax.swing.JPanel panelFixBrokenReferences;
    private javax.swing.JScrollPane scrollBrowseBrokenReferences;
    private javax.swing.JScrollPane scrollFixBrokenReferences;
    private javax.swing.JScrollPane scrollMessageArea;
    private com.l2fprod.common.swing.JTaskPane taskpaneBrokenReferences;
    private com.l2fprod.common.swing.JTaskPaneGroup taskpaneGrpFindBrokenReferences;
    private com.l2fprod.common.swing.JTaskPaneGroup taskpaneGrpFixBrokenReferences;
    private javax.swing.JTable tblBrowseBrokenReferences;
    private javax.swing.JTree treeFixBrokenReferences;
    private javax.swing.JTextArea txtMessageArea;
    // End of variables declaration//GEN-END:variables
    
    
    class BrokenReferencesTableModel extends AbstractTableModel {
        private String[] column_names = {"Source", "Current Text" };
        private OOComponentHelper ooDocument;
        private ArrayList<XTextField> orphanedReferences = new ArrayList<XTextField>();
        
        BrokenReferencesTableModel(OOComponentHelper ooDoc, ArrayList<XTextField> orphaned){
            this.ooDocument=ooDoc;
            this.orphanedReferences = orphaned;
        }

        public int getRowCount() {
            return orphanedReferences.size();
        }

        public int getColumnCount() {
            return this.column_names.length;
        }

         public String getColumnName(int column) {
                return this.column_names[column];
         }
         
         public Class getColumnClass(int col) { 
                return String.class;
         }
         
         private String getPropertyOfField (XTextField aField, String propName) {
             String propValue = "";
            try {
                propValue = AnyConverter.toString(this.ooDocument.getObjectPropertySet(aField).getPropertyValue(propName));
            } catch (UnknownPropertyException ex) {
                    log.error("exception: " + ex.getClass().getName() + " : " + ex.getMessage());
            } catch (WrappedTargetException ex) {
                    log.error("exception: " + ex.getClass().getName() + " : " + ex.getMessage());
            } catch (com.sun.star.lang.IllegalArgumentException ex) {
                    log.error("exception: " + ex.getClass().getName() + " : " + ex.getMessage());
            } finally {
             return propValue;
            }
         }
        public Object getValueAt(int rowIndex, int columnIndex) {
            XTextField mField = this.orphanedReferences.get(rowIndex);
            switch (columnIndex) {
                case 0:
                    return mField.getPresentation(true);
                    
                case 1:
                   
                    return mField.getPresentation(false);

                default:
                    return new String("unknown column");
            }
        }
        
    }
}
