/*
 * editorApplicationController.java
 *
 * Created on May 30, 2007, 11:22 AM
 */

package org.bungeni.editor.dialogs;

import com.sun.star.beans.PropertyValue;
import com.sun.star.comp.helper.Bootstrap;
import com.sun.star.frame.XController;
import com.sun.star.frame.XDispatchHelper;
import com.sun.star.frame.XDispatchProvider;
import com.sun.star.frame.XModel;
import com.sun.star.lang.XComponent;
import com.sun.star.text.XText;
import com.sun.star.text.XTextDocument;
import com.sun.star.uno.Exception;
import com.sun.star.uno.UnoRuntime;
import com.sun.star.uno.XComponentContext;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.HashMap;
import java.util.Properties;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.apache.webdav.lib.WebdavResource;
import org.bungeni.db.BungeniClientDB;
import org.bungeni.db.DefaultInstanceFactory;
import org.bungeni.db.QueryResults;
import org.bungeni.db.SettingsQueryFactory;
import org.bungeni.editor.BungeniEditorProperties;
import org.bungeni.ooo.BungenioOoHelper;
import org.bungeni.utils.BungeniDataReader;
import org.bungeni.utils.CommonFileFunctions;
import org.bungeni.utils.FileTableModel;
import org.bungeni.utils.Installation;
import org.apache.log4j.Logger;
import org.bungeni.utils.MessageBox;
import org.bungeni.utils.WebDavStore;
import org.bungeni.utils.WebDavTableModel;
import org.bungeni.utils.WorkspaceFolderTableModel;

/**
 * Controller Class for Main Swing Openoffice UNO management application
 * @author Ashok Hariharan
 */
public class editorApplicationController extends javax.swing.JPanel {
    private  XComponentContext m_xContext;
    private java.util.Properties m_propSettings;
    private Installation m_installObject;
    private static String __WINDOW_TITLE__ = "Bungeni Editor Client ";
    private WebDavStore m_dav;
    
    //path to settings.properties
    private String m_iniFilePath;
    
    private String m_settings_WorkspacePath;
    private String m_settings_ServerIP;
    private String m_settings_ServerPort;
    private String m_settings_ServerPath;
    private String m_settings_ServerUser;
    private String m_settings_ServerPassword;
   
    private static org.apache.log4j.Logger log = org.apache.log4j.Logger.getLogger(editorApplicationController.class.getName());
    private String m_FullWorkspacePath ;
    private String m_FullTemplatesPath ;
    private String m_currentTemplate;  
    private String m_currentSelectedWorkspaceFile;
    private String m_settings_CurrentTemplate;
    private org.bungeni.editor.dialogs.editorTabbedPanel panel;
    private String m_FullFilesPath;
    private org.bungeni.ooo.BungenioOoHelper openofficeObject;
    /**
     * Constructor for editorApplicationController Class
     */
    public editorApplicationController() {
        initComponents();
    }
    
    /**
     * Main constructor for the class, initializes Panels and oOo environment
     * @param context Openoffice component context
     */
    public editorApplicationController(XComponentContext context) {
        log.debug("in constructor");
        m_xContext = context;
        m_FullWorkspacePath = "";
        m_FullTemplatesPath = "";
        m_currentSelectedWorkspaceFile = "";
        m_iniFilePath = "";
        m_propSettings = new java.util.Properties();
        m_dav = new WebDavStore();
        initComponents();
        CommonFileFunctions cfsObject=new CommonFileFunctions();
         m_installObject = new Installation();
        File dir =m_installObject.getInstallDirectory(this.getClass());
        //code to read properties file
        
        initDocumentTypesModel();
        initProperties(dir);
         //init panels
        initFileTableModels(dir);
        initWorkspaceFolderModels(dir);
        initPanels(dir);
        //initWebDav();
        initDataReader();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        editorAppTabbedPane = new javax.swing.JTabbedPane();
        tabCurrentFile = new javax.swing.JPanel();
        createNewDocument = new javax.swing.JButton();
        lblCurrentTemplate = new javax.swing.JLabel();
        lblCurrentTemplateText = new javax.swing.JLabel();
        cboDocumentTypes = new javax.swing.JComboBox();
        lblDocumentTypes = new javax.swing.JLabel();
        tabTemplates = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTemplatesList = new javax.swing.JTable();
        lblTemplatePath = new javax.swing.JLabel();
        lblSelectedTemplate = new javax.swing.JLabel();
        btnSetCurrentTemplate = new javax.swing.JButton();
        tabWorkspace = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblWorkspaceFolder = new javax.swing.JTable();
        lblSelectedFile = new javax.swing.JLabel();
        btnEditWorkspaceDocument = new javax.swing.JButton();
        tabSettings = new javax.swing.JPanel();
        lblWorkspacePath = new javax.swing.JLabel();
        txtWorkspacePath = new javax.swing.JTextField();
        btnBrowseWorkspacePath = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtServerIp = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblServerPort = new javax.swing.JLabel();
        txtServerPort = new javax.swing.JTextField();
        lblServerHomeDir = new javax.swing.JLabel();
        txtServerHomeDir = new javax.swing.JTextField();
        lblCurrentDirectory = new javax.swing.JLabel();
        checkBoxConnectOnStartup = new javax.swing.JCheckBox();
        btnSaveSettings = new javax.swing.JButton();
        tabServer = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblServerFiles = new javax.swing.JTable();
        progressServerFiles = new javax.swing.JProgressBar();
        btnBackOneFolder = new javax.swing.JButton();
        tabAbout = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        createNewDocument.setText("Create New Document....");
        createNewDocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launchFrameActionPerformed(evt);
            }
        });

        lblCurrentTemplate.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblCurrentTemplate.setText("Create a new document from selected template");

        cboDocumentTypes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblDocumentTypes.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblDocumentTypes.setText("Set Active Document mode for editor");

        org.jdesktop.layout.GroupLayout tabCurrentFileLayout = new org.jdesktop.layout.GroupLayout(tabCurrentFile);
        tabCurrentFile.setLayout(tabCurrentFileLayout);
        tabCurrentFileLayout.setHorizontalGroup(
            tabCurrentFileLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tabCurrentFileLayout.createSequentialGroup()
                .addContainerGap()
                .add(tabCurrentFileLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(tabCurrentFileLayout.createSequentialGroup()
                        .add(cboDocumentTypes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 235, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblCurrentTemplateText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 405, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(createNewDocument, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 230, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblCurrentTemplate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 455, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(lblDocumentTypes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 259, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabCurrentFileLayout.setVerticalGroup(
            tabCurrentFileLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tabCurrentFileLayout.createSequentialGroup()
                .addContainerGap()
                .add(lblDocumentTypes)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tabCurrentFileLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(tabCurrentFileLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(lblCurrentTemplateText, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 20, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(32, 32, 32))
                    .add(tabCurrentFileLayout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 19, Short.MAX_VALUE)
                        .add(cboDocumentTypes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(19, 19, 19)))
                .add(lblCurrentTemplate)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(createNewDocument, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 33, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(165, Short.MAX_VALUE))
        );
        editorAppTabbedPane.addTab("Quick Actions", tabCurrentFile);

        tblTemplatesList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTemplatesList);

        btnSetCurrentTemplate.setText("Set Current Template");
        btnSetCurrentTemplate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetCurrentTemplateActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout tabTemplatesLayout = new org.jdesktop.layout.GroupLayout(tabTemplates);
        tabTemplates.setLayout(tabTemplatesLayout);
        tabTemplatesLayout.setHorizontalGroup(
            tabTemplatesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tabTemplatesLayout.createSequentialGroup()
                .addContainerGap()
                .add(tabTemplatesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblTemplatePath, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                    .add(lblSelectedTemplate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 367, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, btnSetCurrentTemplate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 191, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        tabTemplatesLayout.setVerticalGroup(
            tabTemplatesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tabTemplatesLayout.createSequentialGroup()
                .addContainerGap()
                .add(lblTemplatePath)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lblSelectedTemplate, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(21, 21, 21)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 154, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnSetCurrentTemplate)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        editorAppTabbedPane.addTab("Templates", tabTemplates);

        tblWorkspaceFolder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblWorkspaceFolder);

        btnEditWorkspaceDocument.setText("Edit Selected Document..");
        btnEditWorkspaceDocument.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditWorkspaceDocumentActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout tabWorkspaceLayout = new org.jdesktop.layout.GroupLayout(tabWorkspace);
        tabWorkspace.setLayout(tabWorkspaceLayout);
        tabWorkspaceLayout.setHorizontalGroup(
            tabWorkspaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tabWorkspaceLayout.createSequentialGroup()
                .addContainerGap()
                .add(tabWorkspaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                    .add(lblSelectedFile, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 367, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, btnEditWorkspaceDocument, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 197, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        tabWorkspaceLayout.setVerticalGroup(
            tabWorkspaceLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tabWorkspaceLayout.createSequentialGroup()
                .addContainerGap()
                .add(lblSelectedFile, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(17, 17, 17)
                .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 177, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btnEditWorkspaceDocument)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        editorAppTabbedPane.addTab("Workspace", tabWorkspace);

        tabSettings.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblWorkspacePath.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblWorkspacePath.setText("Workspace Path");

        btnBrowseWorkspacePath.setText("Browse..");
        btnBrowseWorkspacePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseWorkspacePathActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11));
        jLabel2.setText("Server IP");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lblServerPort.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblServerPort.setText("Server Port");

        lblServerHomeDir.setFont(new java.awt.Font("Tahoma", 1, 11));
        lblServerHomeDir.setText("Server Home Directory");

        checkBoxConnectOnStartup.setFont(new java.awt.Font("Tahoma", 1, 11));
        checkBoxConnectOnStartup.setText("Connect to Server on Start Up");
        checkBoxConnectOnStartup.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        checkBoxConnectOnStartup.setMargin(new java.awt.Insets(0, 0, 0, 0));

        btnSaveSettings.setText("Save Settings");

        org.jdesktop.layout.GroupLayout tabSettingsLayout = new org.jdesktop.layout.GroupLayout(tabSettings);
        tabSettings.setLayout(tabSettingsLayout);
        tabSettingsLayout.setHorizontalGroup(
            tabSettingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tabSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .add(tabSettingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(tabSettingsLayout.createSequentialGroup()
                        .add(lblCurrentDirectory, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 443, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .add(tabSettingsLayout.createSequentialGroup()
                        .add(tabSettingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(tabSettingsLayout.createSequentialGroup()
                                .add(txtWorkspacePath, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 334, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(btnBrowseWorkspacePath))
                            .add(lblWorkspacePath, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 174, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(tabSettingsLayout.createSequentialGroup()
                                .add(tabSettingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel2)
                                    .add(txtServerIp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE))
                                .add(28, 28, 28)
                                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 60, Short.MAX_VALUE)
                                .add(tabSettingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(txtServerPort, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 107, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(lblServerPort)
                                    .add(checkBoxConnectOnStartup))))
                        .add(92, 92, 92))
                    .add(tabSettingsLayout.createSequentialGroup()
                        .add(lblServerHomeDir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 186, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(468, Short.MAX_VALUE))
                    .add(tabSettingsLayout.createSequentialGroup()
                        .add(txtServerHomeDir, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                        .add(388, 388, 388))))
            .add(tabSettingsLayout.createSequentialGroup()
                .add(208, 208, 208)
                .add(btnSaveSettings, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 145, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(311, Short.MAX_VALUE))
        );
        tabSettingsLayout.setVerticalGroup(
            tabSettingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tabSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .add(tabSettingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(btnBrowseWorkspacePath)
                    .add(tabSettingsLayout.createSequentialGroup()
                        .add(lblWorkspacePath)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtWorkspacePath, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lblCurrentDirectory, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tabSettingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jSeparator1)
                    .add(tabSettingsLayout.createSequentialGroup()
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtServerIp, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(tabSettingsLayout.createSequentialGroup()
                        .add(lblServerPort)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(txtServerPort, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(21, 21, 21)
                .add(lblServerHomeDir)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(tabSettingsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(txtServerHomeDir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(checkBoxConnectOnStartup))
                .add(31, 31, 31)
                .add(btnSaveSettings)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        editorAppTabbedPane.addTab("Settings", tabSettings);

        tblServerFiles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblServerFiles);

        btnBackOneFolder.setText("\u00ab Back one Folder Level");
        btnBackOneFolder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackOneFolder_Clicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout tabServerLayout = new org.jdesktop.layout.GroupLayout(tabServer);
        tabServer.setLayout(tabServerLayout);
        tabServerLayout.setHorizontalGroup(
            tabServerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tabServerLayout.createSequentialGroup()
                .addContainerGap()
                .add(tabServerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(progressServerFiles, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                    .add(jScrollPane3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
                    .add(btnBackOneFolder))
                .addContainerGap())
        );
        tabServerLayout.setVerticalGroup(
            tabServerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(tabServerLayout.createSequentialGroup()
                .add(20, 20, 20)
                .add(btnBackOneFolder)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 175, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(progressServerFiles, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        editorAppTabbedPane.addTab("Server", tabServer);

        org.jdesktop.layout.GroupLayout tabAboutLayout = new org.jdesktop.layout.GroupLayout(tabAbout);
        tabAbout.setLayout(tabAboutLayout);
        tabAboutLayout.setHorizontalGroup(
            tabAboutLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 664, Short.MAX_VALUE)
        );
        tabAboutLayout.setVerticalGroup(
            tabAboutLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 303, Short.MAX_VALUE)
        );
        editorAppTabbedPane.addTab("About", tabAbout);

        jLabel1.setText("Bungeni Editor Application 0.7");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, editorAppTabbedPane, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(editorAppTabbedPane, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 328, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditWorkspaceDocumentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditWorkspaceDocumentActionPerformed
// TODO add your handling code here:
        
        //JOptionPane.showMessageDialog(null, m_currentSelectedWorkspaceFile);
        initoOoAndLaunchFrame(m_currentSelectedWorkspaceFile, false);
        
    }//GEN-LAST:event_btnEditWorkspaceDocumentActionPerformed

    private void btnSetCurrentTemplateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetCurrentTemplateActionPerformed
// TODO add your handling code here:
        String currentlySelectedTemplateinTable = m_settings_CurrentTemplate;
        FileOutputStream fso;
        try {
            fso = new FileOutputStream(m_iniFilePath);
        
        m_propSettings.setProperty("workspace.currenttemplate", currentlySelectedTemplateinTable );
            m_propSettings.store(fso, "" );
        }     catch (FileNotFoundException ex){
             log.debug(m_iniFilePath +" file not found : " + ex.getLocalizedMessage(), ex); 
          } 
               catch (IOException ex) {
            log.debug(ex.getLocalizedMessage(), ex);
        }
    
        
        
    }//GEN-LAST:event_btnSetCurrentTemplateActionPerformed

    private void btnBackOneFolder_Clicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackOneFolder_Clicked
        // TODO add your handling code here:
        //
       WebDavTableModel davModel = (WebDavTableModel) tblServerFiles.getModel();
        String parentPath="";
        try {
            parentPath = davModel.getParentPath("");
        } catch (java.lang.Exception ex) {
            if (ex.getMessage().equals("root-reached")){
                log.info("back one folder - root folder was reached");
                JOptionPane.showMessageDialog(this, "You cannot browser beyond the home folder");
                return;
            }
        }
       log.debug("setting path on prev click = "+ parentPath);
       davModel.setPath(parentPath); 
    }//GEN-LAST:event_btnBackOneFolder_Clicked

    private void btnBrowseWorkspacePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseWorkspacePathActionPerformed
// TODO add your handling code here:
        //launch browse folders dialog box...
        //Create a file chooser
        JFileChooser fc = new JFileChooser();
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        
        int nReturnVal = fc.showOpenDialog(this);
        
        if (nReturnVal == JFileChooser.APPROVE_OPTION) {
                File file = fc.getSelectedFile();
                //This is where a real application would open the file.
               //log.info("Opening: " + file.getName() + ".\n");
               txtWorkspacePath.setText(file.getName());
            } else {
                //log.info("Open command cancelled by user.\n");
            }

    }//GEN-LAST:event_btnBrowseWorkspacePathActionPerformed

    class documentType extends Object {
        String docType;
        String typeDesc;
        String templatePath;
        
        public String toString(){
            return typeDesc;
        }
        
        public String templatePathNormalized() {
               String normalizedPath = templatePath.replace('/', File.separatorChar);
               normalizedPath = DefaultInstanceFactory.DEFAULT_INSTALLATION_PATH() + File.separator + normalizedPath;       
               return normalizedPath;
        }
    }
    
    private void initDocumentTypesModel(){
        documentType[] dtArr = null;
        BungeniClientDB instance = new BungeniClientDB (DefaultInstanceFactory.DEFAULT_INSTANCE(), DefaultInstanceFactory.DEFAULT_DB());
        String query = SettingsQueryFactory.Q_FETCH_ALL_DOCUMENT_TYPES();
        instance.Connect();
        QueryResults qr = instance.QueryResults(query);
        instance.EndConnect();    
        if (qr.hasResults()) {
              Vector<Vector<String>> resultRows  = new Vector<Vector<String>>();
              resultRows = qr.theResults();
              dtArr = new documentType[resultRows.size()];
              int i=0;
                for (Vector<String> resultRow: resultRows) {
                    dtArr[i] = new documentType();
                    dtArr[i].docType =  qr.getField(resultRow, "DOC_TYPE");
                    dtArr[i].typeDesc = qr.getField(resultRow, "DESCRIPTION");
                    dtArr[i].templatePath = qr.getField(resultRow, "TEMPLATE_PATH");
                    i++;
                }
        }
        
        if (dtArr != null) {
            this.cboDocumentTypes.setModel(new DefaultComboBoxModel(dtArr));
        }
    }
    
    private void initWorkspaceFolderModels(File dirStruct){
    log.debug("initializing workspace folder");
    tblWorkspaceFolder.setRowSelectionAllowed(true);
    tblWorkspaceFolder.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    tblWorkspaceFolder.getSelectionModel().addListSelectionListener(new tblWorkspaceFolderRowListener());
    
    String filesFolder = dirStruct.getAbsolutePath()+dirStruct.separator+m_settings_WorkspacePath+dirStruct.separator+"files";
    m_FullFilesPath= filesFolder;
//   m_FullWorkspacePath = dirStruct.getAbsolutePath()+dirStruct.separator+m_settings_WorkspacePath;
    log.debug("files folder = "+filesFolder);
    File filesWSFolder = new File(filesFolder);
    WorkspaceFolderTableModel dirModel = new WorkspaceFolderTableModel(filesWSFolder);
    tblWorkspaceFolder.setModel(dirModel);
}

private void initFileTableModels(File dirStruct ) {
     //lblTemplatePath.setText(dirStruct.getAbsolutePath()+m_settings_WorkspacePath+File.separator+"templates");
       //initialize Table in tab...
       log.debug("initializing templates list table");
        tblTemplatesList.setRowSelectionAllowed(true);
        tblTemplatesList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tblTemplatesList.getSelectionModel().addListSelectionListener(new tblTemplatesListRowListener());
        /*******set up table models******/ 
        // build path to templates file
        String templatesFolder = dirStruct.getAbsolutePath()+dirStruct.separator+m_settings_WorkspacePath+dirStruct.separator+"templates";
        m_FullTemplatesPath = templatesFolder;
        m_FullWorkspacePath = dirStruct.getAbsolutePath()+dirStruct.separator+m_settings_WorkspacePath;
        log.debug("templates folder = "+templatesFolder);
        File fileTemplateFolder = new File(templatesFolder);
        FileTableModel dirModel = new FileTableModel(fileTemplateFolder);
        tblTemplatesList.setModel(dirModel);
        
        
}

private void initPanels(File currentDir){
    //tabSettings.....

    txtServerIp.setText(m_settings_ServerIP);
    txtServerPort.setText(m_settings_ServerPort);
    txtServerHomeDir.setText(m_settings_ServerPath);
    txtWorkspacePath.setText( m_settings_WorkspacePath);
    lblCurrentDirectory.setText("Current Directory : "+currentDir.getAbsolutePath());
}

private void initWebDav(){
    //log.info("initialiazing WebDav");
   // WebDavStore wds = new WebDavStore();
    m_dav.setConnectionUrl("http://" + m_settings_ServerIP);
    m_dav.setConnectionPort(new Integer(m_settings_ServerPort));
    m_dav.setConnectionUsername(m_settings_ServerUser);
    m_dav.setConnectionPassword(m_settings_ServerPassword);
    m_dav.setConnectionBaseDirectory(m_settings_ServerPath);
    
     m_dav.connect("");
    
    /*
    m_dav.connect("");
    WebdavResource dav =wds.getResourceHandle();
    if (dav != null){
        log.info("Successfully connected using Webdav");
        initWebdavTableModel(dav);
    }
    else
        log.debug("Webdav connection failed...");
     */
    initWebdavTableModel();
}



private void initWebdavTableModel(){
    //log.info("initializing webdav table model");
    Component[] cpx = tabTemplates.getComponents();
    for (int i=0; i < cpx.length; i++){
        log.debug("component name = "+ cpx[i].getClass().getName());
    }
    WebDavTableModel davTable = new WebDavTableModel(m_dav, m_settings_ServerPath, tblServerFiles, progressServerFiles);
    davTable.brains();
    tblServerFiles.setModel(davTable);
    tblServerFiles.addMouseListener(new tblServerFilesMouseAdapter());
}


private void initProperties(java.io.File currentFolder) {
        try {
            String iniFilePath = currentFolder.getAbsolutePath()+currentFolder.separator+"settings" +currentFolder.separator +"settings.properties";
            m_iniFilePath = iniFilePath;
            log.debug("Inifile path ="+ iniFilePath);
            FileInputStream fsi = new FileInputStream(iniFilePath);
            log.debug("no. of bytes available = "+ fsi.available() );
            m_propSettings.load(fsi);
            if (m_propSettings.isEmpty()) { log.debug("Empty Settings");}
            else { log.debug( "size is = " + m_propSettings.size()); }
            String firstLaunch = "";
            log.debug("First Launch = "+m_propSettings.getProperty("firstlaunch"));
            firstLaunch = m_propSettings.getProperty("firstlaunch");
            m_settings_WorkspacePath=m_propSettings.getProperty("workspace.folder");
            m_settings_ServerIP=m_propSettings.getProperty("server.ip");
            m_settings_ServerPort=m_propSettings.getProperty("server.port");
            m_settings_ServerPath=m_propSettings.getProperty("server.path");
            m_settings_ServerUser=m_propSettings.getProperty("server.user");
            m_settings_ServerPassword=m_propSettings.getProperty("server.password");
            m_settings_CurrentTemplate = m_propSettings.getProperty("workspace.currenttemplate");
            
            log.debug(" all 4 settings variables "+ m_settings_WorkspacePath  + ", " + m_settings_ServerIP+ ","+ m_settings_ServerPort);
            
        } catch (IOException ex) {
            //log.error(ex.getMessage(), ex);
            }

}
        
private void initFrame(XComponent component){
            javax.swing.JFrame frame = new javax.swing.JFrame("BungeniEditor Control Panel");
            
            panel = new org.bungeni.editor.dialogs.editorTabbedPanel(component, this.openofficeObject, frame);
            //panel.setOOoHelper(this.openofficeObject);
            frame.add(panel);
            WindowListener tabbedPanelListener = new WindowAdapter(){
                  
                public void windowDeiconified(WindowEvent e) {
                        panel.bringEditorWindowToFront();
                        //deiconize all floating panels
                        HashMap<String,org.bungeni.editor.panels.IFloatingPanel> panelMap = panel.getFloatingPanelMap();
                        java.util.Iterator<String> iterPanels = panelMap.keySet().iterator();
                        while (iterPanels.hasNext()) {
                            org.bungeni.editor.panels.IFloatingPanel p = panelMap.get(iterPanels.next());
                            JFrame f= p.getParentWindowHandle();
                            System.out.println("maximizing  other window");
                            f.setExtendedState(f.NORMAL);
                        }
                    }
                    
                    public void windowIconified(WindowEvent e) {
                        System.out.println("panel minimized....");
                        HashMap<String,org.bungeni.editor.panels.IFloatingPanel> panelMap = panel.getFloatingPanelMap();
                        java.util.Iterator<String> iterPanels = panelMap.keySet().iterator();
                        while (iterPanels.hasNext()) {
                            org.bungeni.editor.panels.IFloatingPanel p = panelMap.get(iterPanels.next());
                            JFrame f= p.getParentWindowHandle();
                            System.out.println("minimizing other window");
                            f.setExtendedState(f.ICONIFIED);
                        }

                    }
  
            };
            frame.addWindowListener(tabbedPanelListener);
            //frame.setSize(243, 650);
            frame.setSize(275, 650);
            frame.setResizable(false);
            frame.setAlwaysOnTop(true);
            frame.setVisible(true);
            //prevent closing of main editor panel
            frame.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            //position frame
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            Dimension windowSize = frame.getSize();
            log.debug("screen size = "+ screenSize);
            log.debug("window size = "+ windowSize);
            
            int windowX = 5; //Math.max(0, (screenSize.width  - windowSize.width));
            int windowY = Math.max(0, (screenSize.height - windowSize.height) / 2);
            frame.setLocation(windowX, windowY);  // Don't use "f." inside constructor.
}

private void initoOoAndLaunchFrame(String templatePath, boolean isTemplate){
            openofficeObject = new org.bungeni.ooo.BungenioOoHelper(m_xContext);
            openofficeObject.initoOo();
            
            String templateURL = openofficeObject.convertPathToURL(templatePath);
            XComponent xComponent;
            log.debug("template URL= "+ templateURL);
            if (isTemplate)
                xComponent = openofficeObject.newDocument(templateURL);
            else
                xComponent = openofficeObject.openDocument(templateURL);
            //XTextDocument xTextDocument = (XTextDocument)UnoRuntime.queryInterface(XTextDocument.class, xComponent); 
            //XText xText = xTextDocument.getText();    
            //xText.setString("Hello World!!!!!!!");
            initFrame(xComponent);
}

public void initDataReader(){

/**
     BungeniDataReader rds = new BungeniDataReader();
    Vector<String[]> vMpData = new Vector<String[]>();
    vMpData = rds.read("mps.data");
    System.out.println("size of mp.data = "+ vMpData.size());

 *
 */
}

private void launchFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launchFrameActionPerformed
            //use template defined in m_settings_CurrentTemplate
            //m_FullTemplatesPath
            //m_settings_CurrentTemplate = "hansard.ott";
            String templateURL = "";
            log.debug("Current Template file :" + m_FullTemplatesPath+File.separatorChar+m_settings_CurrentTemplate);
            documentType selectedDocType = (documentType) cboDocumentTypes.getSelectedItem();
            BungeniEditorProperties.setEditorProperty("activeDocumentMode", selectedDocType.docType);
            initoOoAndLaunchFrame(selectedDocType.templatePathNormalized(), true); 
            //dispatchObject.executeDispatch(xDispatchProvider, ".uno:FullScreen", "", 0, args); 
       
           // xController.getFrame().getContainerWindow().setPosSize(0, 0, 100, 100, com.sun.star.awt.PosSize.POS);
            
            
        
            
}//GEN-LAST:event_launchFrameActionPerformed


/**
 * Listener Classes Listed below
 **/



/**
 * Listener Class for JTable listing templates
 * @author Ashok Hariharan
 */
   private class tblTemplatesListRowListener implements ListSelectionListener {
        
       public void valueChanged(ListSelectionEvent event) {
            if (event.getValueIsAdjusting()) {
                return;
            }
            
            String strTemplateName = "";
            strTemplateName = (String) tblTemplatesList.getValueAt(tblTemplatesList.getSelectedRow(), 0);
            m_settings_CurrentTemplate = strTemplateName;
            lblSelectedTemplate.setText("Active Template: " + strTemplateName);
            //  output.append("ROW SELECTION EVENT. ");
          //  outputSelection();
        }
    }

 /**
 * Listener Class for JTable listing templates
 * @author Ashok Hariharan
 */
  private class tblWorkspaceFolderRowListener implements ListSelectionListener {
        
       public void valueChanged(ListSelectionEvent event) {
            if (event.getValueIsAdjusting()) {
                return;
            }
            
            String strFileName = "";
            strFileName = (String) tblWorkspaceFolder.getValueAt(tblWorkspaceFolder.getSelectedRow(), 0);
            lblSelectedFile.setText("Active Template: " + strFileName);
            m_currentSelectedWorkspaceFile = m_FullFilesPath + File.separator + strFileName;
            //  output.append("ROW SELECTION EVENT. ");
          //  outputSelection();
        }
    }

  
  class editorTabbedPanelFrameWindowListener implements WindowListener {
        public void windowOpened(WindowEvent e) {
        }

        public void windowClosing(WindowEvent e) {
            //System.out.println("windowClosing....");
            panel.cleanup();
        }

        public void windowClosed(WindowEvent e) {
        }

        public void windowIconified(WindowEvent e) {
        }

        public void windowDeiconified(WindowEvent e) {
            panel.bringEditorWindowToFront();
        }

        public void windowActivated(WindowEvent e) {
          //  System.out.println("Window Was Activated!");
        }

        public void windowDeactivated(WindowEvent e) {
         //   System.out.println("Window was De-Activated!");
        }
      
  }
/**
 *  Mouse Listener Class for Server file listing 
 *  It checks for "double cick" on the JTable control listing the files from the webdav server
 * @author Ashok Hariharan
 */
private class tblServerFilesMouseAdapter implements MouseListener {
    
    public void mouseClicked(MouseEvent e){
        if (e.getClickCount() == 2){
            Point p = e.getPoint();
            int row = tblServerFiles.rowAtPoint(p);
            String fileName = (String)tblServerFiles.getValueAt(row, 0);
            String fileType = (String) tblServerFiles.getValueAt(row, 3);
            if (fileType.equals("folder")) {
                log.debug("folder: "+fileName + "was clicked");
                //switch to the clicked folder
                //first get the table model
                WebDavTableModel davModel = (WebDavTableModel) tblServerFiles.getModel();
                davModel.brains();
                davModel.setPathRelative(fileName);
            }
            else
                log.debug("file was clicked");
        }
    }

        public void mousePressed(MouseEvent e) {
        }

        public void mouseReleased(MouseEvent e) {
        }

        public void mouseEntered(MouseEvent e) {
        }

        public void mouseExited(MouseEvent e) {
        }

}
   
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackOneFolder;
    private javax.swing.JButton btnBrowseWorkspacePath;
    private javax.swing.JButton btnEditWorkspaceDocument;
    private javax.swing.JButton btnSaveSettings;
    private javax.swing.JButton btnSetCurrentTemplate;
    private javax.swing.JComboBox cboDocumentTypes;
    private javax.swing.JCheckBox checkBoxConnectOnStartup;
    private javax.swing.JButton createNewDocument;
    private javax.swing.JTabbedPane editorAppTabbedPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCurrentDirectory;
    private javax.swing.JLabel lblCurrentTemplate;
    private javax.swing.JLabel lblCurrentTemplateText;
    private javax.swing.JLabel lblDocumentTypes;
    private javax.swing.JLabel lblSelectedFile;
    private javax.swing.JLabel lblSelectedTemplate;
    private javax.swing.JLabel lblServerHomeDir;
    private javax.swing.JLabel lblServerPort;
    private javax.swing.JLabel lblTemplatePath;
    private javax.swing.JLabel lblWorkspacePath;
    private javax.swing.JProgressBar progressServerFiles;
    private javax.swing.JPanel tabAbout;
    private javax.swing.JPanel tabCurrentFile;
    private javax.swing.JPanel tabServer;
    private javax.swing.JPanel tabSettings;
    private javax.swing.JPanel tabTemplates;
    private javax.swing.JPanel tabWorkspace;
    private javax.swing.JTable tblServerFiles;
    private javax.swing.JTable tblTemplatesList;
    private javax.swing.JTable tblWorkspaceFolder;
    private javax.swing.JTextField txtServerHomeDir;
    private javax.swing.JTextField txtServerIp;
    private javax.swing.JTextField txtServerPort;
    private javax.swing.JTextField txtWorkspacePath;
    // End of variables declaration//GEN-END:variables

    
 
    
}
