#!/bin/sh

set -e

echo "Attemting to remove bungeni exist-db update."
echo "Note: Unistalling this update will not undo changes that had already been implemented during installation."
sleep 2

exit 0
