#!/bin/sh
# postinst script for bungeni
set -e

echo "Adding bungeni group and user..."
useradd bungeni
echo "bungeni:bungeni" | chpasswd
echo "Setting Permissions..."
usermod -d /opt/bungeni bungeni
usermod -s /bin/bash bungeni
chown -R bungeni:bungeni /opt/bungeni
update-rc.d bungeni_services defaults

exit 0
