#!/bin/sh

# postinst script for bungeni

set -e

echo "Removing bungeni group and user..."
if [ -z "$(getent passwd bungeni)" ]; then
    echo "user bungeni does not exist!"
else
	deluser bungeni
    echo "user bungeni deleted."
fi

echo "Removing supervisor startup scripts..."
update-rc.d bungeni_services remove

exit 0
