load 'deploy' if respond_to?(:namespace) # cap2 differentiator
Dir['vendor/plugins/*/recipes/*.rb'].each { |plugin| load(plugin) }
load 'config/commonfunctions'
load 'config/dspacecustomconfig'
load 'config/dspacetomcatconfig'
load 'config/dspace_presetup'
load 'config/dspace_setup'
load 'config/dspace_services'
load 'config/dspaceconfigvars'
load 'config/dspace_install'
load 'config/deploy'
