#!/bin/sh

set -e

case "$1" in
	purge)
    ;;
	remove|upgrade|failed-upgrade|abort-install|abort-upgrade)
    
		echo "Portal successfully removed."
    ;;
	disappear)
    ;;
	*)

        echo "prerm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

exit 0
