#!/bin/bash
#===============================================================================
#
#          FILE:  postinst
#
#
#   DESCRIPTION:  Portal postinstall script, sets ownership of portal folder to bungeni user	
#
#       OPTIONS:  configure, abort-upgrade, abort-remove, abort-deconfigure
#          BUGS:  ---
#         NOTES:  ---
#
#       AUTHORS:  Ashok Hariharan <ashok@parliaments.info>
#				  Samuel Weru <samweru@gmail.com>
#
#  ORGANIZATION:  UNDESA
#       VERSION:  ---
#       CREATED:  ---
#      REVISION:  ---
#===============================================================================

case "$1" in
    configure)

		echo "setting portal ownership to bungeni user"
		chown -R bungeni:bungeni /opt/bungeni/bungeni_apps/bungeni/portal
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)
		exit 0
    ;;
    *)
		echo "postinst called with unknown argument \`$1'" >&2
		exit 0
    ;;
esac

exit 0
