#!/bin/sh -e
#===============================================================================
#
#          FILE:  prerm
#
#	DESCRIPTION:  stop bungeni service			
#
#       OPTIONS:  remove, purge
#          BUGS:  ---
#         NOTES:  ---
#
#       AUTHORS:  Ashok Hariharan <ashok@parliaments.info>
#				  Samuel Weru <samweru@gmail.com>
#
#  ORGANIZATION:  UNDESA
#       VERSION:  ---
#       CREATED:  ---
#      REVISION:  ---
#===============================================================================

case "$1" in
	remove|purge)

		echo "stopping services"
		service  bungeni_services stop
    ;;
	*)

        echo "prerm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

exit 0
